feat: add InputLong
molgenis/molgenis-emx2 pull request #1219
Opened 2022-05-05 14:08 UTC by MaxPostema

chore: removed isValidKey code duplication
fix: Add error handeling

2022-05-06 08:07 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputDecimal.vue
> +    validDecimal() {
errorMessage is a better name, since that is what is returned and how it is used in the html

2022-05-06 08:08 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputDecimal.vue
> +      console.log(parseFloat(this.value));
debug lines :P

2022-05-06 08:09 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputDecimal.vue
> +        this.$emit("input", event.target.value);
Just wondering, what if value is NaN ? Should we also return null in that case?

2022-05-06 08:11 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputLong.vue
> +      if (this.value && this.value.length > 0) {
could be:
if (this.value?.length){...}

2022-05-06 08:11 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputLong.vue
> +      if (value.length > 0) {
just if(value.length)

2022-05-06 08:12 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputLong.vue
> +  return undefined;
add else

2022-05-06 08:13 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputLong.vue
> +    longError() {
same as decimalInput, I think errorMessage is a better name for this :) (though I don't mind this one as much)

2022-05-06 12:10 UTC, mswertz submitted a review, later dismissed

2022-05-09 07:02 UTC, connoratrug requested changes
<img width="795" alt="Screenshot 2022-05-09 at 09 00 44" src="https://user-images.githubusercontent.com/47183404/167357062-03369941-e582-4bc7-8044-26ec55c929f1.png">

- errors in console
- can not input a negative number
- not a number input ( no browser number support)

2022-05-09 11:25 UTC, connoratrug approved these changes
would be nice to use a type number imo 
now when you try to type in a negative number you get a flash of a error msg 
error could be done or loose focus or after debounce

2022-05-10 11:46 UTC, merged