fix: show val if previously set in fileInput
molgenis/molgenis-emx2 pull request #1622
Opened 2022-09-20 06:51 UTC by connoratrug

2022-09-20 18:53 UTC, mswertz requested changes
Well spotted that this should be possible. I agree with comment of max it now looks odd with only '.csv' so suggest to change by adding simply the name of the input (there is no name of the file).

2022-09-20 18:53 UTC, mswertz commented on apps/molgenis-components/src/components/forms/InputFile.vue
> +    </div>
Indeed. in the explorer it simply gets the name of the input (there is no 'name' for a file). 
Should we do the same here?
See https://emx2.dev.molgenis.org/pet%20store/tables/#/User

2022-09-20 18:53 UTC, mswertz commented on apps/molgenis-components/src/components/forms/InputFile.vue
> +    </div>
Might also include size then.

2022-09-21 07:21 UTC, connoratrug commented
This pr is about moving the file component form the styleguide to the molgenis components lib, the "Previous value:.. 
 was missing. The name of the file is part of the upload and should be stored in the backend and part of the response when fetching the file data. suggest to do that fix in a separate PR

2022-09-21 08:48 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputFile.vue
> +    </div>
If there never is a file name here, maybe instead change the message to something like: 'Extension of previous upload: {{value.extension}}'?

2022-09-22 13:31 UTC, merged