chore: Set jenkins pods resource limits
molgenis/molgenis-emx2 pull request #1718
Opened 2022-10-10 09:29 UTC by connoratrug

- setting limit only sets requests equal to limit

2022-10-12 06:46 UTC, christianhilbrands requested changes
see comment above, could you write it like the example code given above?

2022-10-12 08:45 UTC, connoratrug commented
> see comment above, could you write it like the example code given above?

why ? why not have i the same , you seem to no more about this that i do , please update the PR the way you think it should be.

2022-10-13 07:04 UTC, mswertz commented on Jenkinsfile
> +                        "c-l4svj:molgenis-helm3-emx2 " +
Has this changed again?

2022-10-13 07:05 UTC, christianhilbrands commented on Jenkinsfile
> +                        "c-l4svj:molgenis-helm3-emx2 " +
yes

2022-10-13 08:26 UTC, christianhilbrands approved these changes
LGTM

2022-10-13 08:27 UTC, merged