removed dublets and added decimal and text
molgenis/molgenis-emx2 pull request #1753
Opened 2022-10-20 14:05 UTC by erikzwart

Removed dublets and added decimal and text in order to load ds-dictionaries into catalogue.

2022-10-20 14:06 UTC, erikzwart commented
![](https://github.trello.services/images/mini-trello-icon.png) [#9244 As datamanager I want to clean up the catalogue](https://trello.com/c/b4EUrS3G/536-9244-as-datamanager-i-want-to-clean-up-the-catalogue)

2022-10-20 14:42 UTC, mswertz approved these changes

2022-10-20 14:43 UTC, mswertz requested changes
build breekt omdat de voorbeeld data er niet bij matcht.

2022-10-21 11:59 UTC, erikzwart commented
De test klaagt over het volgende:
org.molgenis.emx2.datamodels.TestLoaders > testDataCatalogueLoader FAILED
    Transaction failed: insert or update on table "SourceVariables" violates foreign key constraint "SourceVariables.format REFERENCES Formats".Key (format)=(int) is not present in table "Formats".: Cannot commit transaction

Aangezien ik nu niet precies weet welke test plus data ik zou moeten aanpassen heb ik 'int' terug geplaatst naar Formats.csv. Wellicht nu verwarrend dat int en integer beide te kiezen zijn.

Het bestand Conception.xlsx verwijdert omdat test data gebaseerd is op een oud data model.

Conception-acc gebruikt het Format character, we kunnen deze omzetten naar string of text. Of character toevoegen aan Formats.

issues met Formats voor data-catalogue en data-catalogue-staging zijn opgelost.

2022-10-21 12:07 UTC, erikzwart commented
question: are we still using the folder/data Cohorts? (https://github.com/molgenis/molgenis-emx2/tree/master/data/datacatalogue/Cohorts)

2022-10-24 19:25 UTC, mswertz approved these changes

2022-10-25 12:59 UTC, merged