Feat: individual queries that use case-level variant data
molgenis/molgenis-emx2 pull request #1783
Opened 2022-10-31 15:08 UTC by joerivandervelde

Added case-level data to genomic variants which is linked to Individuals. Subsequently, a refback in Individuals allows queries on variants case-level data such as clinical relevance. For instance, this finds all Individuals that have a pathogenic variant:

```
{
  "query": {
    "filters": [
      {
        "type": "HP_0045088",
        "id": "NCIT_C168799",
        "operator": "="
      }
    ]
  }
}
```

2022-11-16 14:42 UTC, mswertz requested changes
small changes.

2022-11-20 19:42 UTC, joerivandervelde commented on backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Column.java
> +    return table.equals(column.table) && columnName.equals(column.columnName);
fixed by adding schema name to this equals()

2022-11-20 19:42 UTC, joerivandervelde commented on backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/beaconv2/Beaconv2_ModelEndpointsTest.java
> +        """
fixed

2022-11-21 09:28 UTC, mswertz approved these changes

2022-11-21 12:40 UTC, merged