fix: settings and JWT default secret
molgenis/molgenis-emx2 pull request #1918
Opened 2022-12-21 21:27 UTC by mswertz

2022-12-22 09:38 UTC, chinook25 approved these changes

2022-12-22 11:43 UTC, joerivandervelde requested changes
Does not seem to work as intended yet, see comment in code

2022-12-22 11:43 UTC, joerivandervelde commented on backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
> +        key = getSetting(Constants.MOLGENIS_JWT_SHARED_SECRET);
getSetting(Constants.MOLGENIS_JWT_SHARED_SECRET) always returns null after server restart, even if there is a key present. This results in a new key being generated and thereby invalidating existing tokens.

2023-01-09 07:18 UTC, joerivandervelde approved these changes
Problem is indeed fixed

2023-01-09 09:03 UTC, merged