Feat/add aggregate view to tables
molgenis/molgenis-emx2 pull request #1935
Opened 2022-12-30 13:14 UTC by MaxPostema

todo: make it look better

2023-01-24 15:37 UTC, mswertz requested changes
It is a tiny bit confusing: what if we make a pull down from the 'view' so you can select views from a list?

Also it is unclear for me how to chose the 'row labels' and 'column labels'. I think it would helpt to move the form therefore to a seperate line and add labels to the select boxes.

if there is only one categorical value then hide the select, see https://preview-emx2-pr-1935.dev.molgenis.org/pet%20store/tables/#/Pet?_view=aggregate&_limit=1 where you can only group by category.

If there is no categorical value, then give an warning message that says 'Aggregate view not available: there is no ref/ontology columns available to group by on'.

I have loaded the 'datacatalogue3' including demo data and then expected here a group by https://preview-emx2-pr-1935.dev.molgenis.org/catelogue/tables/#/Cohorts?_view=aggregate&_limit=1 => don't understand why no group by is shown?

You might benefit from a quick phonecall.

2023-01-24 15:37 UTC, mswertz commented on apps/molgenis-components/src/components/tables/AggregateOptions.vue
> +        this.$emit("update:selectedColumnHeader", this.refColumns[0]);
interesting approach to update the props. Didn't know this is possible

2023-01-26 09:31 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/AggregateOptions.vue
> +      this.refColumns = this.getRefTypeColumns(this.columns as IColumn[]);
This as feels dangerous, maybe rewrite and use defineProps()

2023-01-26 12:24 UTC, mswertz approved these changes

2023-01-26 13:27 UTC, merged