fix: variable harmonization summary table
molgenis/molgenis-emx2 pull request #2144
Opened 2023-03-08 15:10 UTC by marijevdgeest

Closes #2140

2023-03-08 18:45 UTC, mswertz approved these changes
oops

2023-03-20 11:05 UTC, mswertz requested changes
need to check again

2023-05-03 08:25 UTC, erikzwart approved these changes

2023-05-03 08:33 UTC, erikzwart commented
Closes https://github.com/molgenis/molgenis-emx2/issues/2140

2023-05-03 08:33 UTC, merged