feat: add isCollapsed prop
molgenis/molgenis-emx2 pull request #2179
Opened 2023-03-22 11:24 UTC by chinook25

2023-03-24 09:18 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/RefTable.vue
> +              <div v-if="reference.metadata">
metadata is mandatory so this if can be removed

2023-03-24 09:22 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/RefTable.vue
> +}
this should be part of the initialisation e.g. ref(startCollapsed && canCollapse);

2023-03-24 11:36 UTC, mswertz requested changes
Looks great. 

For 'ref' and 'ontology' I propose we don't collapse.

For 'ref_array' and 'ontology_array' I propose that you collapse when [more than one item] AND [number of columns > 5] 

I also found a bug, see 
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/120060/227511104-e043c409-e1e7-4c83-97f3-409571713ded.png">

To get this view go to 
https://preview-emx2-pr-2179.dev.molgenis.org/catalogue/tables/#/CollectionEvents

2023-03-27 11:46 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/DataDisplayCell.vue
> +        : typeMap[this.metaData?.columnType] || "StringDisplay";
metadata is required, so I do not approve of this monkey patch. This should be fixed at the input side.

2023-03-27 11:47 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/RefTable.vue
> +);
minor thingy, let's put computeds together if possible, in order to keep to files more clean.

2023-03-28 11:28 UTC, chinook25 commented on apps/molgenis-components/src/components/tables/TableExplorer.vue
>        @onClose="refSideModalProps = undefined"
questionmarks here are not necessary (because of the v-if)

2023-03-28 21:41 UTC, mswertz approved these changes

2023-03-30 07:03 UTC, merged