fix(client): graphql query expansion bring server to its knees
molgenis/molgenis-emx2 pull request #2202
Opened 2023-03-30 08:10 UTC by mswertz

2023-03-30 08:42 UTC, connoratrug commented
query fails for preview -> CatalogueOntologies -> Diseases

```
{
  "errors" : [
    {
      "message" : "Error: Validation error of type SubSelectionRequired: Sub selection required for type [Diseases] of field children @ 'Diseases/parent/children'"
    }
  ]
}
```

2023-03-30 08:44 UTC, connoratrug commented on apps/molgenis-components/src/client/client.ts
this function needs a js test, due to its (increased complexity )  ( see test folder for how to setup simple test ) , test should test generated query. and also serves as documentation for query generation.

2023-03-30 08:49 UTC, connoratrug requested changes
https://preview-emx2-pr-2202.dev.molgenis.org/CatalogueOntologies/tables/#/Diseases

see error

2023-03-30 09:01 UTC, connoratrug commented
children heeft nu geen sub-select meer, dat moet wel omdat het geen eind punt is 

```query Diseases($filter: DiseasesFilter, $orderby: Diseasesorderby) {
  Diseases(filter: $filter, limit: 20, offset: 0, orderby: $orderby) {
    order
    name
    label
    parent {
      order
      name
      label
      parent {
        name
      }
      codesystem
      code
      ontologyTermURI
      definition
      children
      mg_draft
      mg_insertedBy
      mg_insertedOn
      mg_updatedBy
      mg_updatedOn
    }
    codesystem
    code
    ontologyTermURI
    definition
    children {
      order
      name
      label
      parent {
        name
      }
      codesystem
      code
      ontologyTermURI
      definition
      children
      mg_draft
      mg_insertedBy
      mg_insertedOn
      mg_updatedBy
      mg_updatedOn
    }
    mg_draft
    mg_insertedBy
    mg_insertedOn
    mg_updatedBy
    mg_updatedOn
  }
  Diseases_agg(filter: $filter) {
    count
  }
} # Write your query or mutation here
````

2023-03-30 10:09 UTC, connoratrug commented on apps/molgenis-components/src/client/client.ts
> +  rootLevel: boolean = true
param rootLevel  is only used in for recursion stop, function should have (non recursive) public api without rootlevel param that calls private (recursive) function where the rootLevel is set to true only on the initial kickoff

2023-03-30 10:31 UTC, connoratrug commented on apps/molgenis-components/src/client/client.ts
see basic test setup for column string generation ( from table-meta)  , currently the generator fails to add the required subSelection for children

2023-03-30 14:39 UTC, mswertz commented
> Cohorts table (https://preview-emx2-pr-2202.dev.molgenis.org/UMCG/tables/#/Cohorts) gives this error:
> 
> Error: Validation error of type SubSelectionRequired: Sub selection required for type Institutions of field institution @ 'Cohorts/institution/providerOf/institution'
> 
> Diseases last page does not load

Okay, that is a ref_array. Should be expanding so probably some boolean logic still off.

2023-03-31 06:38 UTC, BrendaHijmans reviewed
Functional review: last page of Diseases ontology loads quickly: https://preview-emx2-pr-2202.dev.molgenis.org/CatalogueOntologies2/tables/#/Diseases.

Form for Subcohorts does not open in UMCG schema: 
![image](https://user-images.githubusercontent.com/42644481/229042308-75802829-9e13-44e3-b98d-11ca13010271.png)

Diseases do not load in form:
![image](https://user-images.githubusercontent.com/42644481/229042620-d40b8b5f-96ae-46fd-a944-852759219ead.png)

2023-03-31 10:10 UTC, merged