fix: enable array options for hyperlink and email inputs
molgenis/molgenis-emx2 pull request #2247
Opened 2023-04-19 10:42 UTC by chinook25

2023-04-19 10:55 UTC, YpeZ approved these changes

2023-04-20 06:39 UTC, mswertz requested changes
Ik had op preview volgende probleem
- ik kon in formulier wel editen zoals verwacht
- maar ik kreeg de resultaten niet terug (is dat een backend ding dat ik moet aanpakken?)
- 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/120060/233280472-fadb76f3-ef66-400a-bc9a-f87a9899e001.png">

2023-04-26 09:46 UTC, MaxPostema approved these changes

2023-05-02 11:24 UTC, mswertz approved these changes

2023-05-02 11:46 UTC, merged