feat: add AUTO_ID column type, with optional computed expression of form 'pre${mg_autoid}post'
molgenis/molgenis-emx2 pull request #2311
Opened 2023-05-17 12:54 UTC by connoratrug

remaining todo:
- [ ] shorter autoid.

2023-05-23 20:55 UTC, mswertz approved these changes
I have refactored to have an AUTO_ID column. So probably you should review before merging. Looks good to me.

N.B. I noticed an unrelated bug that in schema editor I cannot add columns for a new table until I have saved the schema first.

2023-05-24 05:26 UTC, dtroelofsprins reviewed
I've tested the auto_id, having a specific dataType is a good thing I think. The computed field with the comment on how you should define the pre-post fix is nice, so you don't have to look it up first in the documentation. 
Functionality works fine, also with adding pre and post fixes. Would be nice if you could define the length of the autoID yourself as you can do in EMX1. But perhaps this is not possible as in EMX1 a sequence (with or without scrambler) is used, and uniqueness is guaranteed in this way (if you define the length according to the max number of rows you expect of course). Don't know if this also holds for these type of autoID values.

2023-05-24 07:48 UTC, connoratrug commented on apps/molgenis-components/src/components/forms/RowEdit.vue
> +      if (column.columnType === "AUTO_ID") {
use const , see other const for impl exsample

2023-05-24 07:49 UTC, connoratrug commented on apps/molgenis-components/src/components/forms/RowEdit.vue
should expect sample/demo to be updated to include new column type

2023-05-24 07:51 UTC, connoratrug commented on apps/schema/src/components/ColumnEditModal.vue
> +                  column.columnType !== 'AUTO_ID'
replace with named function ( computed ) , maybe; 'isEditable(column)'

2023-05-24 08:09 UTC, chinook25 submitted a review, later dismissed
Code looks good, just some minor code things. 
However when testing I found a bug: If I add an autoId column without computed it doesn't generate when adding or editing a row. When I edit it the row, the field shows in the form as just a string input (editing this string also gets saved).

When used with computed it seems to work fine and actually shows the ids.

2023-05-24 08:55 UTC, dtroelofsprins requested changes
Found a bug (?) when trying to update a row with an autoID including a computed expression:
![image](https://github.com/molgenis/molgenis-emx2/assets/57137088/a49aa420-d47b-47f7-bbcd-6e40fce18554)

And if you don't include the computed expression with pre/post fix, an update of the row works, but the ID, get "undefined"...

2023-05-24 17:39 UTC, mswertz commented on apps/molgenis-components/src/components/forms/FormInput.vue
> +          description="Header description"
yes, this is what I meant with annoying formatting.

2023-05-24 18:45 UTC, mswertz commented on apps/molgenis-components/src/components/forms/RowEdit.vue
updated pet store

2023-05-24 18:45 UTC, mswertz commented
> Found a bug (?) when trying to update a row with an autoID including a computed expression: ![image](https://user-images.githubusercontent.com/57137088/240545951-a49aa420-d47b-47f7-bbcd-6e40fce18554.png)
> 
> And if you don't include the computed expression with pre/post fix, an update of the row works, but the ID, get "undefined"...

Solved

2023-05-24 21:46 UTC, merged