fix: Order variable fetch
molgenis/molgenis-emx2 pull request #2462
Opened 2023-06-26 09:47 UTC by connoratrug

Closes #2412

2023-06-26 10:15 UTC, mswertz requested changes
In general variable explorer, when I set filter on 'networks' then I see no effect.

2023-06-26 10:17 UTC, mswertz commented
> In general variable explorer, when I set filter on 'networks' then I see no effect.

Hmm, this also doesn't work in the master

2023-06-26 10:37 UTC, EleanorHyde-UMCG approved these changes
Getest met dev: Athlete_CDM wordt wel geselecteerd wanneer erom wordt gevraagd. General variable explorer lijkt ook goed te zijn.

2023-06-28 08:30 UTC, mswertz approved these changes

2023-06-28 09:38 UTC, merged