chore: add e2e playwright to ci
molgenis/molgenis-emx2 pull request #2466
Opened 2023-06-27 09:05 UTC by mswertz

2023-07-07 07:28 UTC, MaxPostema requested changes
I feel like we are making a bit of a mess in the living room.

'e2eTests' and 'tests-examples' Is adding a  "camelCase"  and "kebab-case" directory.

to more fit into the style of the repo maybe:
'e2e/tests' and 'e2e/samples'

Or use "kebab-case" for both directories, we already use it for "helm-chart".

2023-07-10 07:32 UTC, chinook25 approved these changes
Looks fine to me, not sure how I can test whether the CI works.

2023-07-10 07:32 UTC, chinook25 commented on tests-examples/demo-todo-app.spec.ts
> +import { test, expect, type Page } from '@playwright/test';
This file can be deleted I'd say.

2023-07-10 07:59 UTC, mswertz commented
> I feel like we are making a bit of a mess in the living room.
> 
> 'e2eTests' and 'tests-examples' Is adding a "camelCase" and "kebab-case" directory.
> 
> to more fit into the style of the repo maybe: 'e2e/tests' and 'e2e/samples'
> 
> Or use "kebab-case" for both directories, we already use it for "helm-chart".

LOL. I am happy to rename to e2e/tests and take it from there

2023-07-10 11:33 UTC, chinook25 commented on e2e/README.md
> +```npx playwright test```
yarn?

2023-07-10 11:33 UTC, chinook25 commented on e2e/settings.gradle
empty file?

2023-07-10 12:18 UTC, merged