fix(InputRefback): when spaces in primary key column names and when deleting. closes #2570
molgenis/molgenis-emx2 pull request #2616
Opened 2023-08-13 21:24 UTC by mswertz

2023-08-14 10:04 UTC, chinook25 requested changes
This PR breaks the last example of the InputRefSelect (Example with filter (category.name = dog))

2023-08-15 07:22 UTC, mswertz commented on apps/molgenis-components/src/components/forms/InputRefSelect.vue
> +        @focus="showSelect = true && !this.readonly"
indeed, LOL

2023-08-15 11:52 UTC, chinook25 approved these changes

2023-08-15 11:52 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputRefSelect.vue
> +          v-if="modelValue && !this.readonly"
remove 'this.'

2023-08-15 20:14 UTC, merged