feat: data model and dashboards for ern-cranio
molgenis/molgenis-emx2 pull request #2634
Opened 2023-08-15 09:35 UTC by davidruvolo51

2023-10-03 08:14 UTC, chinook25 requested changes
Mostly looks good. Haven't tested yet.

2023-10-03 08:14 UTC, chinook25 commented on apps/molgenis-viz/src/utils/utils.js
> +  const response = await fetch(url, {
replace with client?

2023-10-03 11:59 UTC, davidruvolo51 commented on apps/cranio-public/README.md
Removed file

2023-10-03 12:03 UTC, davidruvolo51 commented on apps/cranio-public/src/styles/index.scss
> +  font-family: Helvetica, sans-serif;
That's a good idea. In the next version of the molgenis-viz library, I'm planning on consolidating many of the styles into the main css file, and create more sass mixins.

2023-10-03 12:03 UTC, davidruvolo51 commented on apps/cranio-public/src/styles/index.scss
> +  font-family: Helvetica, sans-serif;
For now, I'll leave it in

2023-10-03 12:04 UTC, davidruvolo51 commented on apps/molgenis-viz/src/components/viz/ChartLegend.vue
> +    // a unique ID for the legend
The comments are for the vuese doc generator.

2023-10-03 12:04 UTC, davidruvolo51 commented on apps/molgenis-viz/src/components/viz/GroupedColumnChart.vue
> +
Same as above. The comments are for the molgenis-viz documentation.

2023-10-03 12:06 UTC, davidruvolo51 commented on apps/molgenis-viz/src/components/viz/GaugeChart.vue
> +      // default: '#c7eae5'
The primary components in the molgenis-viz library have documentation written in the file. The markup is used to generate the user manuals and provide an overview on the default values.

2023-10-03 14:06 UTC, davidruvolo51 commented on apps/cranio-public/src/utils/utils.js
> +      "Content-Type": "application/json",
Removed!

2023-10-03 14:07 UTC, davidruvolo51 commented on apps/cranio-provider/src/utils/utils.js
> +  const response = await fetch(url, {
Done!

2023-10-04 06:44 UTC, davidruvolo51 commented on apps/cranio-provider/src/components/AppFooter.vue
> +            <!-- more links here -->
Removed.

I plan on adding this component to the `molgenis-viz` library and using named slots. At the time the component was created, it wasn't clear how many projects would use this footer component or the default molgenis footer.

2023-10-04 06:44 UTC, davidruvolo51 commented on apps/cranio-provider/README.md
Deleted

2023-10-04 09:53 UTC, chinook25 approved these changes

2023-10-04 09:56 UTC, merged