Fix for issue #2361.
molgenis/molgenis-emx2 pull request #2735
Opened 2023-09-13 08:29 UTC by konstantina-gkp

2023-09-13 20:07 UTC, mswertz requested changes
we need to fix tests, can you already run them on your machine?

2023-09-14 09:08 UTC, clemens-tolboom commented
I noticed the code is not on par with latest master but on master(28 august)

2023-09-15 06:58 UTC, mswertz approved these changes

2023-09-15 07:17 UTC, connoratrug requested changes
see sonar issues

2024-09-13 09:02 UTC, closed without merging