fix(schema): make sure computed field can display errors
molgenis/molgenis-emx2 pull request #2849
Opened 2023-10-11 12:16 UTC by MaxPostema

2023-10-18 11:06 UTC, mswertz approved these changes

2023-10-19 12:18 UTC, chinook25 requested changes
Existing expressions only start triggering in the preview after being modified e.g.
pet store -> orders -> price
Also, validation is not triggering in the forms anymore.

2023-10-19 12:18 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/RowEdit.vue
> +        if (column.visible === "" && this.columnErrors[column.id] !== "") {
Would it not be better to have !column.visible && !this.columnErrors[column.id] ?
Because I don't think all errors are initialized on ""

2023-11-29 15:23 UTC, MaxPostema commented
Not getting it to work, closing for now

2023-11-29 15:23 UTC, closed without merging