model update: publications as table
molgenis/molgenis-emx2 pull request #292
Opened 2021-06-16 13:53 UTC by BrendaHijmans

2021-06-17 10:20 UTC, mswertz requested changes
I have only one request for change. Then you merge AFAIC.

2021-06-17 10:20 UTC, mswertz commented on data/datacatalogue/molgenis.csv
> -Resources,,publication,text,,,,,,,,Marker publication(s) about this resource
Ik zou de 'marker publication' graag behouden en daarnaast een ref_array naar publications voor als ze meer willen.

2021-06-24 07:25 UTC, BrendaHijmans commented on data/datacatalogue/molgenis.csv
> -Resources,,publication,text,,,,,,,,Marker publication(s) about this resource
ik heb de markerPublication nu toegevoegd, maar als ref (niet text)

2021-06-29 11:55 UTC, sidohaakma commented
![](https://github.trello.services/images/mini-trello-icon.png) [model update: publications as table](https://trello.com/c/wdHLUuos/144-model-update-publications-as-table)

2021-06-30 07:51 UTC, mswertz approved these changes

2021-06-30 07:51 UTC, merged