feat: Enhancements on the Directory App
molgenis/molgenis-emx2 pull request #2955
Opened 2023-11-10 11:06 UTC by konstantina-gkp

The following issues have been fixed:

- The contact and head information is displayed on the biobank (side) card.
- The AlsoKnownIn urls are displayed on biobank, collection and network cards.
- The Quality Standards information is being retrieved from QualityStandards table and is displayed on the according cards. 
- Age unit and range is displayed on the collection card.

2023-11-10 11:53 UTC, chinook25 reviewed
Some minor comments, but in general the code looks good. I didn't do any testing on it, just code review ;)

2023-11-10 11:53 UTC, chinook25 commented on apps/directory/src/components/report-components/ReportDetailsList.vue
> +            <span class="mg-icon-text">{{ value.label ? value.label : 'Website' }}</span>
Instead of ternary you could use the js shorthand "value.label || 'Website'". Don't need to change it, but for future code ;)

2023-11-10 11:53 UTC, chinook25 commented on apps/directory/src/functions/viewmodelMapper.js
>  import { sortCollectionsByName } from "./sorting";
It would be good to have unit tests for the functions in this file

2023-11-10 11:53 UTC, chinook25 commented on apps/directory/src/property-config/initialBiobankColumns.js
> +        showOnBiobankCard: true,
file needs (auto-)layouting

2023-11-10 11:53 UTC, chinook25 commented on apps/directory/src/stores/qualitiesStore.js
> +              definition: quality.definition
readd the comma here

2023-11-10 12:44 UTC, mswertz reviewed
looks good, so when approval from Esther/Dieuwke on functionality and Joris on code you can merge.

2023-11-10 14:17 UTC, esthervanenckevort requested changes
Most of it looks fine, but when testing it on my local machine I noticed that the Quality and the age are missing.

In the Safari web console I see the following error:
```
[Error] Unhandled Promise Rejection: Error: Validation error (FieldUndefined@[QualityStandards]) : Field 'QualityStandards' in type 'Query' is undefined: {"response":{"errors":[{"message":"Validation error (FieldUndefined@[QualityStandar...
	(anonymous function) (index.86b05c13.js:116:502)
```

2023-11-10 14:28 UTC, konstantina-gkp commented
> Most of it looks fine, but when testing it on my local machine I noticed that the Quality and the age are missing.
> 
> In the Safari web console I see the following error:
> 
> ```
> [Error] Unhandled Promise Rejection: Error: Validation error (FieldUndefined@[QualityStandards]) : Field 'QualityStandards' in type 'Query' is undefined: {"response":{"errors":[{"message":"Validation error (FieldUndefined@[QualityStandar...
> 	(anonymous function) (index.86b05c13.js:116:502)
> ```

@dtroelofsprins send me a new data model which includes the table QualityStandards and AgeUnit. Until I switched to the new database, I also had the same error message.

2023-11-10 14:37 UTC, esthervanenckevort commented
> > Most of it looks fine, but when testing it on my local machine I noticed that the Quality and the age are missing.
> > In the Safari web console I see the following error:
> > ```
> > [Error] Unhandled Promise Rejection: Error: Validation error (FieldUndefined@[QualityStandards]) : Field 'QualityStandards' in type 'Query' is undefined: {"response":{"errors":[{"message":"Validation error (FieldUndefined@[QualityStandar...
> > 	(anonymous function) (index.86b05c13.js:116:502)
> > ```
> 
> @dtroelofsprins sent me a new data model which includes the table QualityStandards and AgeUnit. Until I switched to the new database, I also had the same error message.

So the new data model should be part of this PR

2023-11-13 05:54 UTC, dtroelofsprins commented
> > > Most of it looks fine, but when testing it on my local machine I noticed that the Quality and the age are missing.
> > > In the Safari web console I see the following error:
> > > ```
> > > [Error] Unhandled Promise Rejection: Error: Validation error (FieldUndefined@[QualityStandards]) : Field 'QualityStandards' in type 'Query' is undefined: {"response":{"errors":[{"message":"Validation error (FieldUndefined@[QualityStandar...
> > > 	(anonymous function) (index.86b05c13.js:116:502)
> > > ```
> > 
> > 
> > @dtroelofsprins sent me a new data model which includes the table QualityStandards and AgeUnit. Until I switched to the new database, I also had the same error message.
> 
> So the new data model should be part of this PR

I wanted indeed test it with the latest data model, but the preview is still v8.221.4, so I can't upload the defaultValues in here.

2023-11-13 11:48 UTC, dtroelofsprins requested changes
I did a functional test:

- Age items (age_low, age_high and age_unit) are shown OK again
- Both contact and head info is on biobank and collection card => shown differently, perhaps for later.
- Also Known In is on all three cards, showing a weblink, which you can click (place in the detail list differs, perhaps for later)
- Qualities are shown again on the biobank and collection card, after adjusting the table to Quality Standards. 
- However the green checkmark on the general app page at the Biobank Name is gone. Did some testing => with the new model it does even work with the App without these adjustments. Old model with the new App also works.
- Didn’t test the solve bug in the star model => better that Aneas tests this.

2023-11-14 10:00 UTC, esthervanenckevort approved these changes
The changes that we agreed during standup have been resolved. Other issues are going into new issues and PRs

2023-11-15 05:44 UTC, dtroelofsprins approved these changes

2023-11-16 09:28 UTC, merged