fix: validation of array type input fields in molgenis-components
molgenis/molgenis-emx2 pull request #3062
Opened 2023-11-28 09:58 UTC by konstantina-gkp

Array type input fields in molgenis-components were not properly validated when marked as required. The issue has been fixed. Each individual field in an array input component is now validated separately.

2023-11-29 09:22 UTC, chinook25 requested changes
Test needs update

2023-11-29 15:13 UTC, MaxPostema approved these changes

2023-12-01 08:41 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
> +  };
I'd like this function to be extracted and tested separately.

2023-12-11 09:28 UTC, chinook25 approved these changes

2023-12-11 09:33 UTC, merged