fix: Main catalogue about page fails to load #3112
molgenis/molgenis-emx2 pull request #3113
Opened 2023-12-08 14:59 UTC by connoratrug

Closes #3112

2023-12-08 15:34 UTC, BrendaHijmans requested changes
The page does load, but the information is about the UMCG research data catalogue. So that should be fixed also. Shall we write a text on Monday?

2023-12-11 08:47 UTC, connoratrug commented
> The page does load, but the information is about the UMCG research data catalogue. So that should be fixed also. Shall we write a text on Monday?

This is not related to the pr , please create a separate story this.

2023-12-11 10:34 UTC, BrendaHijmans commented
> > The page does load, but the information is about the UMCG research data catalogue. So that should be fixed also. Shall we write a text on Monday?
> 
> This is not related to the pr , please create a separate story this.

I think it is related, because it will lead to faulty information being displayed for the data catalogue. Can we do a conditional, as Morris suggested? If theme is UMCG, display about, else do not display about?

2023-12-11 12:20 UTC, BrendaHijmans approved these changes

2023-12-11 12:22 UTC, merged