fix: don't show withdrawn biobanks and collections
molgenis/molgenis-emx2 pull request #3132
Opened 2023-12-13 11:14 UTC by chinook25

Don't show collections and biobanks in search results that have been withdrawn.

fixes #3015

2024-01-09 15:40 UTC, esthervanenckevort requested changes
The code works mostly, only if a collection is marked as withdrawn that collection is still visible in the biobank details screen and the collections details screen is missing the banner that says that the collection is longer part of the Directory.

2024-01-10 06:16 UTC, dtroelofsprins reviewed
Regarding Esther remark: only if a collection is marked as withdrawn that collection is still visible
It seems that no filtering on withdrawn collections is done at all, because when looking at the collection counts all collections are accounted for.

2024-01-10 09:37 UTC, MaxPostema approved these changes

2024-01-12 09:32 UTC, dtroelofsprins approved these changes
Checked the counts too quickly, forgot that the count fix was not yet included in this PR. So the counts are OK.

2024-01-12 11:41 UTC, merged