fix: match-all filter in directory app
molgenis/molgenis-emx2 pull request #3440
Opened 2024-02-27 16:25 UTC by konstantina-gkp

fixes: #3393
Adjusted emx2 query builder to support “and” operation for “match-all” filter.
Initially the query for “match-all” filter was:

```{
Biobanks(orderby: { name: ASC }, filter: { _and: [ { collections: { categories: { name: { equals: ["covid19", "paediatric_only"] } } } } ] }) {
    juridical_person,
    id,
    name,
    withdrawn,
    quality {,
        quality_standard {
            name
        }
    },
    collections(orderby: { id: ASC }, filter: { _and: [ { categories: { name: { equals: ["covid19", "paediatric_only"] } } } ] }) {
        id,
        size,
        name,
        withdrawn,
        type {
            label,
            name
```
Now the query for "match-all"is:
```
{
Biobanks(orderby: { name: ASC }, filter: { _and: [ { collections: { categories: { name: { equals: "covid19" } } } }, { collections: { categories: { name: { equals: "paediatric_only" } } } } ] }) {
    juridical_person,
    id,
    name,
    withdrawn,
    quality {,
        quality_standard {
            name
        }
    },
    collections(orderby: { id: ASC }, filter: { _and: [ { categories: { name: { equals: "covid19" } } }, { categories: { name: { equals: "paediatric_only" } } } ] }) {
        id,
        size,
        name,
        withdrawn,
        type {
            label,
            name
```

2024-02-29 11:30 UTC, dtroelofsprins requested changes
I've tested several filter combinations, some of them go OK, some of then don't

- Country => when I select two country to match all => result should be no biobanks found, but query gets stuck (infinite). This also holds for other filters where I select more options and the result should be no biobanks found.
- When I select Categories to match all paediatric and covid19, result = 0 collections, count is indeed 0, but 5 biobanks are shown (this should be none). This also happens with other options.
- ~~When I select paediatric_included and covid19, counts are OK, but when I than select a third one (rare_disease) there should be no biobanks found, however, 1 biobank with one (sub) collection is shown.~~ This is actual a bug in the production version!

2024-02-29 11:35 UTC, konstantina-gkp commented
This is a separate issue and not related to the current fix/issue. The "match-all" option works as intended. I have reported the new issue [here](https://github.com/molgenis/molgenis-emx2/issues/3445).

2024-02-29 11:56 UTC, dtroelofsprins approved these changes

2024-02-29 13:18 UTC, chinook25 requested changes
some code technical comments, but functionally it works :)

2024-02-29 13:18 UTC, chinook25 commented on apps/molgenis-components/src/queryEmx2/queryEmx2.ts
> +      operator = "equals";
Don't do input modification.
I suggest making a getGqlOperator function for this

2024-02-29 13:18 UTC, chinook25 commented on apps/molgenis-components/src/queryEmx2/queryEmx2.ts
> +    for (const value of valueArray) {
You're shadowing `value` here, don't do that unless there is a good reason to.

2024-02-29 13:18 UTC, chinook25 commented on apps/molgenis-components/src/queryEmx2/queryEmx2.ts
> +      /** reverse the path, so we can build it from the inside out */
try to avoid terms like `it` in comments. I guess it's `the filter`?

2024-03-07 13:24 UTC, chinook25 approved these changes
Just one small thing, if you remove the comment you can merge :)

2024-03-07 13:24 UTC, chinook25 commented on apps/molgenis-components/src/queryEmx2/queryEmx2.ts
> +  /** set the correct operators for graphQl */
This comment does not correctly describe what the function does, it gets, not sets. Please remove, the function name already sufficiently tells what it does. 
In general, only use comments to explain weird code that can't be written comprehensively (e.g. regexes) or for references.

2024-03-07 13:57 UTC, merged