feat(directory): Orphanet hierarchy
molgenis/molgenis-emx2 pull request #3480
Opened 2024-03-11 08:21 UTC by dtroelofsprins

how to test:
- Model + DiseaseTypes update: Go to the preview, login and check table DiseaseTypes. The Diagnosis available filter is broken due to these changes!

todo:
- [na] updated docs in case of new feature
- [na] added tests

2024-03-11 08:21 UTC, dtroelofsprins commented
![](https://github.trello.services/images/mini-trello-icon.png) [#10680 Add parent child information to Orphanet codes in the diseases table](https://trello.com/c/XCvmHsMj/1583-10680-add-parent-child-information-to-orphanet-codes-in-the-diseases-table)

2024-03-13 08:44 UTC, esthervanenckevort commented
Ik zie bij als parents bij ORPHA:443909 (Hereditary nonpolyposis colon cancer) de volgende codes geeft:

- ORPHA:271835 (Genetic digestive tract tumor)
- ORPHA:425003 (Inherited digestive cancer-predisposing syndrome)
- ORPHA:557492 (group of disorders)
- ORPHA:589746 (Inherited gynecological cancer-predisposing syndrome)
 
En bij ORPHA:144 (Lynch syndrome) de volgende codes als parent:

- ORPHA:377788 (disease)
- ORPHA:443909 (Hereditary nonpolyposis colon cancer)
- ORPHA:557493 (disorder)

Ik denk dat we ORPHA:377788 (disease), ORPHA:557493 (disorder) en ORPHA:557492 (group of disorders) niet nodig hebben als parents. Je wilt degene die als een van de parents ORPHA:557492 (group of disorders) aan het begin van je boomstructuur hebben staan. Anders moet je altijd beginnen met group of disorders open te klikken en heb je onder disorder en disease nog steed heel lange lijsten van dezelfde codes.

2024-03-15 10:07 UTC, esthervanenckevort reviewed
Spot checked the hierarchy and it looks good.

Now we still need a developer to fix the diagnosis filter, until then it cannot be merged.

2024-03-26 09:59 UTC, esthervanenckevort commented on data/biobank-directory/ontologies/DiseaseTypes.csv
A couple of entries that still need to be filtered out:
- ORPHA:top
- ORPHA:https://creativecommons.org/licenses/by/4.0/
- ORPHA:C001 clinical entity
- ORPHA:557493 disorder
- ORPHA:557492 group of disorders
- ORPHA:377788 disease
- ORPHA:557494 subtype of a disorder (all entries below that should still be accessible through the main type)

The inactive clinical entity hierarchy should be kept, so people can still search for codes that are no longer active, but might have been used in the past.

2024-03-26 14:06 UTC, chinook25 commented on apps/directory/src/filter-config/filterOptions.ts
> +              );
Comment for code reviewer: changes start with these lines

2024-03-26 14:32 UTC, chinook25 commented
Code changes also seem to resolve #3502

2024-03-26 15:29 UTC, esthervanenckevort requested changes
Code changes look fine. Some remaining issues:
- I still see the issue in #3502 on the preview server. Either fix it in this PR or fix it separately and make sure the issue is not closed with this PR.
- The search only shows the top level code(s) under which the matching code is 
- The Orphanet data still contains a few items that should be removed. See the separate comment about that. @dtroelofsprins

2024-03-26 16:08 UTC, chinook25 commented
>     * I still see the issue in [Diagnosis search hangs when searching for leukemia #3502](https://github.com/molgenis/molgenis-emx2/issues/3502) on the preview server. Either fix it in this PR or fix it separately and make sure the issue is not closed with this PR.
Removed the comment, let's let that in a separate PR in order to not bloat this one too much. 

>     * The search only shows the top level code(s) under which the matching code is
Can you elaborate? Search behaviour is the same as it currently is on master, and works for me. If we want it changed it's better to make that it's own story.

2024-03-27 10:17 UTC, esthervanenckevort commented
> Can you elaborate? Search behaviour is the same as it currently is on master, and works for me. If we want it changed it's better to make that it's own story.

When you search for "Lynch" you see the three main categories under which "Lynch" falls, but you don't see the matching code itself, because the tree is in a collapsed state. This makes it unclear for a user if there was a match found and requires additional steps of digging down the tree to select "Lynch". Showing the parents is good, but I think it is better if we open the tree so you can also see the match. I'll create a separate story for that.

2024-03-28 10:37 UTC, esthervanenckevort approved these changes
The Orphanet code hierarchy is now also clean.

2024-03-28 13:36 UTC, konstantina-gkp approved these changes

2024-03-28 14:19 UTC, merged