feat: expand de-selection down the tree
molgenis/molgenis-emx2 pull request #3629
Opened 2024-04-10 13:12 UTC by connoratrug

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added tests
- [ ] updated testplan to include a test for this fix, including ref to bug using # notation

2024-04-10 14:17 UTC, connoratrug commented on apps/tailwind-components/components/input/Tree.vue
> -    mobileDisplay?: boolean;
code cleanup remove unused props

2024-04-10 14:19 UTC, connoratrug commented on apps/tailwind-components/components/input/Tree.vue
> +      deSelectionList = deSelectionList.concat(expandSelection(node));
expand selection return a expansion list , it can bew used for either selection of deselection

2024-04-11 07:52 UTC, chinook25 requested changes
All the vue files contain typescript errors, these should be fixed before merging.
This PR also brings back the old problem of `Error: Cannot find module '...\molgenis-emx2\apps\node_modules\node_modules\nuxt\bin\nuxt.mjs'` So I can't do a functional test :(

2024-04-11 07:55 UTC, connoratrug commented
> All the vue files contain typescript errors, these should be fixed before merging. This PR also brings back the old problem of `Error: Cannot find module '...\molgenis-emx2\apps\node_modules\node_modules\nuxt\bin\nuxt.mjs'` So I can't do a functional test :(

can you point to a error ts in a file ? , might be an issue on your local machine ?

2024-04-12 09:36 UTC, chinook25 approved these changes

2024-04-12 10:12 UTC, merged