feat(directory): directory staging area template
molgenis/molgenis-emx2 pull request #3634
Opened 2024-04-11 11:27 UTC by dtroelofsprins

how to test:
- goto preview ... and see that the template biobank_directory_staging is available. Test (including demo data) by create a database with this template. 

=> In case the DirectoryOntologies schema is not yet there, it may take a while. If the schema is there it should be finished really quick.

todo:
- [na] updated docs in case of new feature
- [x] added tests
- [na] updated testplan to include a test for this fix, including ref to bug using # notation

2024-04-11 12:12 UTC, esthervanenckevort approved these changes

2024-04-11 14:01 UTC, konstantina-gkp approved these changes

2024-04-12 07:55 UTC, esthervanenckevort requested changes
Functionality works, just minor code conventions issue to be fixed

2024-04-12 08:17 UTC, dtroelofsprins commented on backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/BiobankDirectoryLoader.java
> +    String LOCATION = "biobank-directory/";
It's lowercase now, will remember it for the next time :-)

2024-04-12 08:39 UTC, esthervanenckevort approved these changes

2024-04-12 09:14 UTC, merged