feat: Filter variables on cohort variable mapping
molgenis/molgenis-emx2 pull request #3656
Opened 2024-04-19 10:33 UTC by connoratrug

Closes #3193

- Split list filter into list and filter part
- Move list to component lib, and add demo page
- Add cohort filter to variables page default filter config
- Add option to pass custom filterCondition build function to Filter type

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added tests
- [ ] updated testplan to include a test for this fix, including ref to bug using # notation

2024-04-23 22:25 UTC, mswertz approved these changes
functional approve. Maybe a second programmer look at the code? Otherwise okay to merge (I scanned through it).

2024-04-25 08:16 UTC, connoratrug commented
these seems to be some confusion on what is being shown on the variables list page, https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables and https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/LongITools/variables.

The title seems to suggest the list includes all variables ( in case of subcatalogue; linked to subcatalogue ). However in https://github.com/molgenis/molgenis-emx2/issues/3193 there is the request to be able to filter the variable list on cohorts that are liked to the variable via a mapping ( see this pr for implementation details). 

This seems confusing/inconsistent, so the question becomes;

- What problem is the screen trying to solve, do we want to show all available variables or all mapped variabels ( and why )?
    - if we only want to show mapped variabels, is this made clear though the current (sub)title (_A complete overview of available variables._)  ( then we would need to change the list query to only show the variables that are used in a mapping)
- Should we provide the option to view either the mapped variabels or all the variables ( are these both relevant in the context of the user story ) 
- If we do want to show all variables ( not only mapped ), should we then change the cohort filter query ? , or make it clear via the filter title and description that applying a cohort filter also now includes a mapping filter ( then we should also change the list filter when a cohort filter is active )

2024-04-25 08:55 UTC, marijevdgeest commented
I get your confusion (I think this is really a case where I'm so used to this set up that I don't see this logic anymore). 
I think we need to either decide where we want to show source variables: 
- On the cohort page like we discussed before? (Then it's hard to browse but it's also a feature to have that info in the cohort's context) -> variable explorer needs different titel or explanatory text
- In the variable explorer -> possibly some changes to set up/filters needed.

@EleanorHyde-UMCG @timcadman any thoughts?

2024-05-01 08:52 UTC, mswertz reviewed
I get an list of variables with no mappings in this case (might it be that there 'no match' statuses in here?)

<img width="941" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/56b62b48-68ce-4d7d-ad8f-0e94962091d8">

2024-05-01 09:12 UTC, marijevdgeest commented
> I get an list of variables with no mappings in this case (might it be that there 'no match' statuses in here?)
> 
> <img alt="image" width="941" src="https://private-user-images.githubusercontent.com/120060/327086791-56b62b48-68ce-4d7d-ad8f-0e94962091d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTQ4MTcsIm5iZiI6MTcxNDU1NDUxNywicGF0aCI6Ii8xMjAwNjAvMzI3MDg2NzkxLTU2YjYyYjQ4LTY4Y2UtNGQ3ZC1hZDhmLTBlOTQ5NjIwOTFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQwOTA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTExOWJmNGJlZThhMzUxZTZjYWJjNDA2YjM4NjE5ZjgzZWFlMWYwMTIzODdmMjk2ZTMwYjE5ZDE4YzhiYTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6DFjbG6ysYz94_S0hU7uEKWgL1lW-B6tT0aCl1QZxas">

Indeed no data, I see the matrix also disappeared including cohort name

2024-05-01 09:19 UTC, connoratrug commented
i'll have a look , please be exact with your 'how to reproduce' ( add steps, expected and actual). need to figure out if its a code issue and or a data issue

2024-05-01 09:22 UTC, connoratrug commented
@mswertz @marijevdgeest , i can not reproduce your findings, please add exact steps on how to reproduce

2024-05-02 10:17 UTC, BrendaHijmans submitted a review, later dismissed
De cohort filter doet nu wat hij moet doen: filteren op de variabelen die vanuit een geselecteerd cohort zijn gemapt. Als de repeats van een variabele zijn gemapt, wordt de 'root' variabele ook getoond, dat klopt ook. Er is echter een inconsistentie nu met de matrix als je doorklikt. In het cohort filter worden namelijk de 'na' mappings meegenomen, maar in de overview per variabele niet. Hieronder in stappen met plaatjes uitgelegd.

1. Ga in de preview naar https://preview-emx2-pr-3656.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables
2. selecteer testCohort 2, zie dat er twee variabelen zijn gemapt voor dit cohort 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/1bab5e7f-e554-410d-93b6-ccb1318ab5be)

3. klik op testVariableRepeats_
4. Zie dat testCohort2 niet tussen de harmonisation overview staat voor deze variabele en zijn repeats 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/546a1bf6-b2bf-4e23-a003-335ab1c00968)
5. Dit komt doordat mappings met 'match' = 'na' wel in de cohort filter worden meegenomen, maar niet in de harmonisation overview. Zie hier de data in Variable mappings tabel: 
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/64429644-24de-4bfe-9448-76d180115c47)

2024-05-02 10:41 UTC, connoratrug commented
> De cohort filter doet nu wat hij moet doen: filteren op de variabelen die vanuit een geselecteerd cohort zijn gemapt. Als de repeats van een variabele zijn gemapt, wordt de 'root' variabele ook getoond, dat klopt ook. Er is echter een inconsistentie nu met de matrix als je doorklikt. In het cohort filter worden namelijk de 'na' mappings meegenomen, maar in de overview per variabele niet. Hieronder in stappen met plaatjes uitgelegd.
> 
> 1. Ga in de preview naar https://preview-emx2-pr-3656.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables
> 2. selecteer testCohort 2, zie dat er twee variabelen zijn gemapt voor dit cohort
>    ![image](https://private-user-images.githubusercontent.com/42644481/327393187-1bab5e7f-e554-410d-93b6-ccb1318ab5be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDY2ODgsIm5iZiI6MTcxNDY0NjM4OCwicGF0aCI6Ii80MjY0NDQ4MS8zMjczOTMxODctMWJhYjVlN2YtZTU1NC00MTBkLTkzYjYtY2NiMTMxOGFiNWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEwMzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OWE4YzIyYzNlMTkwMjUwMGQ0YmQzZDZhMDU4YzFjMTU2MWVkYjQzMmQxOGEzZWE4ZTQ3MGYwNDQ2ZmFhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q3nBhHB2ifbfgs5KACkOWNVPk6kYDlQChpheGiAFOe4)
> 3. klik op testVariableRepeats_
> 4. Zie dat testCohort2 niet tussen de harmonisation overview staat voor deze variabele en zijn repeats
>    ![image](https://private-user-images.githubusercontent.com/42644481/327393514-546a1bf6-b2bf-4e23-a003-335ab1c00968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDY2ODgsIm5iZiI6MTcxNDY0NjM4OCwicGF0aCI6Ii80MjY0NDQ4MS8zMjczOTM1MTQtNTQ2YTFiZjYtYjJiZi00ZTIzLWEwMDMtMzM1YWIxYzAwOTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEwMzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjhiYjIzZmQ0NDRkYmRmYzYzZTk4YjllY2YxNTFiMjY5OGZkZDJkMjgyYmY1Zjg2MTI0NTI2NDZlYmIyNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uevdXXyzgESqygGS8rYDElbw2lZvrbNnHtrYjxvu3ag)
> 5. Dit komt doordat mappings met 'match' = 'na' wel in de cohort filter worden meegenomen, maar niet in de harmonisation overview. Zie hier de data in Variable mappings tabel:
>    ![image](https://private-user-images.githubusercontent.com/42644481/327394286-64429644-24de-4bfe-9448-76d180115c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDY2ODgsIm5iZiI6MTcxNDY0NjM4OCwicGF0aCI6Ii80MjY0NDQ4MS8zMjczOTQyODYtNjQ0Mjk2NDQtMjRkZS00YmZlLTk0NDgtNzZkMTgwMTE1YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEwMzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDgxODNiZWJlOTMxNDA4MWM1MDExOGY3NWFmYWU3NWY5YjFjYzQ2MTk2MzU4YTc3Yzc0MzBkNzdmNGJhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ugzeYwGhiho_FM0GT05WgcRZjJn3FdNgiPczWmr6I-I)

This is not related to the current this PR, suggest to submit a issue or feature request

2024-05-03 14:01 UTC, mswertz requested changes

2024-05-03 14:01 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +                  source: { equals: conditions.map((c) => ({ id: c.name })) },
I believe this should also filter on match = 'partial' or  match = 'complete' (e.g. this data https://preview-emx2-pr-3656.dev.molgenis.org/catalogue-demo/tables/#/VariableMappings?_filter=match&match=[{%22name%22:%22complete%22},{%22name%22:%22partial%22}])

2024-05-03 14:01 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +                    source: { equals: conditions.map((c) => ({ id: c.name })) },
idem

2024-05-03 14:07 UTC, EleanorHyde-UMCG commented
If I only select on testcohort2, I should see no variables at all. Now I see testVarNoRepeats and testVarRepeats_.  

The number of cohorts, however, is correct (see discussion on #cohorts_federation Slack - this may solve that problem)

2024-05-03 14:33 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +                  source: { equals: conditions.map((c) => ({ id: c.name })) },
solution is to add `match: { name: { equals: [ "complete" ,"partial"] }} `

2024-05-06 13:08 UTC, mswertz commented
> If I only select on testcohort2, I should see no variables at all. Now I see testVarNoRepeats and testVarRepeats_.
> 
> The number of cohorts, however, is correct (see discussion on #cohorts_federation Slack - this may solve that problem)

We have pushed a fix for this, please check again

2024-05-06 13:24 UTC, EleanorHyde-UMCG commented
> > If I only select on testcohort2, I should see no variables at all. Now I see testVarNoRepeats and testVarRepeats_.
> > The number of cohorts, however, is correct (see discussion on #cohorts_federation Slack - this may solve that problem)
> 
> We have pushed a fix for this, please check again

FIltering on testcohort2 does not show no variables at all.

However, new edge case found right now: the number of cohorts is correct EXCEPT when there are no mappings to be shown. Filter on variable name 'cat' and you get testvarCategorical, with the text "1 variable in 4 cohorts". This should be "1 variable in 0 cohorts" because this variable has not been mapped to in any of the 4 cohorts.

2024-05-06 13:41 UTC, EleanorHyde-UMCG commented
> > > If I only select on testcohort2, I should see no variables at all. Now I see testVarNoRepeats and testVarRepeats_.
> > > The number of cohorts, however, is correct (see discussion on #cohorts_federation Slack - this may solve that problem)
> > 
> > 
> > We have pushed a fix for this, please check again
> 
> FIltering on testcohort2 now shows no variables at all, correct.
> 
> However, new edge case found right now: the text with the number of cohorts is correct EXCEPT when there are no mappings to be shown. Filter on variable name 'cat' and you get testvarCategorical, with the text "1 variable in 4 cohorts". This should be "1 variable in 0 cohorts" because this variable has not been mapped to in any of the 4 cohorts.

Have just discussed that we will leave off the 'in xx variables' text to avoid confusion.

2024-05-06 18:26 UTC, mswertz commented
> Have just discussed that we will leave off the 'in xx variables' text to avoid confusion.

done

2024-05-06 18:26 UTC, mswertz approved these changes

2024-05-07 12:56 UTC, mswertz commented
> Tested and it works correctly.
> 
> One thought is that currently the behaviour when ticking all cohorts is the same as when ticking none. Intuitively I would expect if no cohorts are selected, no data is shown. Could an option be that by default/on initial search all available cohorts ticked, and the user can chose to deselect cohorts which are not needed?
> 
> I'm also happy for this to be classed an enhancement and considered later (perhaps if we get similar feedback from users)

I indeed would like to have that as refinement, i.e., the option to only show variables that have mappings by one or more cohorts vs all variables defined in the network.

2024-05-07 14:22 UTC, timcadman approved these changes

2024-05-07 16:20 UTC, merged