fix: pm app fixes
molgenis/molgenis-emx2 pull request #3671
Opened 2024-04-26 13:08 UTC by davidruvolo51

What are the main changes you did:
- fixed calculations: in the project planning view, I adjusted the formulas to prevent a issue where calculations were larger than they actually are.
- Added free text field: added notes to the person planning view
- HTML/CSS fixes:
    - Table header: multispan columns are properly marked up
    - "Nested rows" were structured to ensure cell/header links
    - Table header is now sticky
    - Adjusted border styling to align with multispan column headers
    - Adjusted padding throughout the table to increase the readability of the table

how to test:
- explain here what to do to test this (or point to unit tests)

todo:

2024-04-26 16:53 UTC, mswertz commented
+button doesn't work in my case
<img width="1621" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/2c13bce1-382f-494c-9f59-90c260fd67a2">

2024-04-26 16:54 UTC, mswertz requested changes
+ button didn't work in my case
<img width="1621" alt="image" src="https://github.com/molgenis/molgenis-emx2/assets/120060/0dc7cacd-73b2-426a-807a-0be318dfacbf">

2024-04-26 16:57 UTC, mswertz commented
> * button didn't work in my case
> 
might be problem elsewhere.

2024-04-29 17:49 UTC, davidruvolo51 commented
It is unclear where the issue is. There is no error, warning, or event when add button is clicked. I think there may be an issue with the import of the `EditModal` in the [RowButtonEdit component at line 25](https://github.com/molgenis/molgenis-emx2/blob/d06e651e868c25a2fc49c0e0dc1959c801b6c565/apps/molgenis-components/src/components/tables/RowButtonEdit.vue#L25). When running locally, I'm seeing a lot of "unresolved import" warnings. Declaring the import in the RowButtonEdit component causes the build of `molgenis-components` to fail. Perhaps that is causing the issue, but it's really hard to tell.

2024-05-03 12:25 UTC, davidruvolo51 commented
Fixed import `EditModal` in the `RowButtonAdd` component

2024-05-03 13:27 UTC, mswertz approved these changes

2024-05-03 13:27 UTC, mswertz commented on apps/molgenis-components/src/components/tables/RowButtonAdd.vue
> +  loader: () => import("../forms/EditModal.vue"),
ah, right

2024-05-03 13:43 UTC, merged