Feat: RPM & DEB package building
molgenis/molgenis-emx2 pull request #3677
Opened 2024-04-29 12:43 UTC by DickPostma

What are the main changes you did:
- Creating Debian and Redhat packages for easy deployment.
- 
how to test:
- Add the corresponding repository's and 

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-05-03 13:29 UTC, mswertz reviewed
when would a package be published to nexus? or will that be another PR? we could for now cherry pick a 'LTS' by hand. However, if we want to do rapid deploys like we now do but then using this then we should publish an 'experimental' package at every release.

2024-05-16 09:01 UTC, EleanorHyde-UMCG commented
> Create a process What is a stable release ? @EleanorHyde-UMCG

Can you give a bit more context? Stable release of what?

2024-05-17 13:24 UTC, DickPostma commented
> > Create a process What is a stable release ? @EleanorHyde-UMCG
> 
> Can you give a bit more context? Stable release of what?

Sorry @EleanorHyde-UMCG i was supposed to type this in the internal issue's. But we need to put up an process (as stated in the roadmap day) to cherry pick an stable release. Let's discuss this later on face2face.

2024-05-17 13:25 UTC, DickPostma commented
$NEXUS_USER and $NEXUS_PASS are not available in the shell script anymore?
The ci-build image needs the rpm package.

2024-06-06 07:55 UTC, DickPostma commented
Waiting on selecting a stable version before release.

2024-06-13 12:43 UTC, DickPostma commented
I talked with @GeriekeBeen. We are gonna start with 10.79.2 as a first stable release.

2024-06-19 05:32 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +# Install Molgenis emx2 as a system service
In overige documentatie wordt MOLGENIS met hoofdletters geschreven. emx2 = EMX2 (al wordt dit in sommige delen van de documentatie ook weggelaten).

2024-06-19 05:43 UTC, dtroelofsprins requested changes
Only reviewed the run_systemd.md. If the command line in this doc is OK I cannot judge as I didn't test this. Only had some textual comments.

2024-06-19 05:43 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +We Support redhat and ubuntu based installations.
Support = support
Daarnaast wellicht Redhat en Ubuntu met hoofdletters? (ik weet niet hoe deze normaal gerefereerd worden).

2024-06-19 05:43 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +Molgenis-emx2 runs on java > 17
idem voor MOLGENIS EMX2. 
Daarnaast staat in de installation guide: Install java (we use adopt [OpenJDK 17](https://adoptium.net/)). Ik draai ook op 17.

2024-06-19 05:43 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +Molgenis-emx2 depends on Posgresql 15
MOLGENIS EMX2
Posgresql bevat een typefout

2024-06-19 05:43 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +In most cases you can proxy_pass traffic to molgenis-emx2 with an (hard of software) loadbalancer to the molgenis-emx2 (port 8080) endpoind.
an = a
of = or
endpoind = endpoint

2024-06-19 05:43 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +A example of nginx proxy pass:
A = An

2024-06-20 08:21 UTC, Fernananas approved these changes
Tested run_systemd.md for ubuntu server. Result; molgenis server was installed and website could be reached. OK

2024-06-20 17:45 UTC, dtroelofsprins commented on docs/molgenis/run_systemd.md
> +# Install Molgenis emx2 as a system service
Wellicht hier ook nog even naar MOLGENIS EMX2 aanpassen(?).

2024-06-25 11:58 UTC, merged