Feat/beacon premissions
molgenis/molgenis-emx2 pull request #3846
Opened 2024-06-04 14:44 UTC by harmbrugge

What are the main changes you did:
- To support all Beacon use-cases, we need 2/3 new authority levels:
Exists (boolean yes/no response to queries)
Range (inexact number of results found)
Count (number of results found, i.e. number of rows of 1 type)

how to test:
- Not working yet
todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-06-11 12:44 UTC, mswertz approved these changes
if Joeri approves functionally then you are ready to go.

2024-06-11 12:44 UTC, mswertz commented on backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/endpoints/EntryTypes.java
>  import spark.Request;
principieel zou je liefst de Request/Response niet nodig hebben hier. Want nu heb je onnodige dependency. Liefst pass je wat je nodig hebt. Kan dat? Of is dat teveel nu (je zit met oude code en dus even zo houden dan maar?)

2024-06-12 12:32 UTC, joerivandervelde requested changes
Looks great, but I would like to request an additional 'count' permission to allow fine-grained discovery for rare disease use cases.

2024-06-12 13:16 UTC, harmbrugge commented
> Looks great, but I would like to request an additional 'count' permission to allow fine-grained discovery for rare disease use cases.

Agreed: added a count user allowing to see count queries with results < 10

2024-06-12 13:18 UTC, joerivandervelde approved these changes
Great to also have COUNT :)

2024-06-12 17:42 UTC, merged