feat: #3790 add topic select to contact form
molgenis/molgenis-emx2 pull request #3875
Opened 2024-06-13 11:20 UTC by connoratrug

What are the main changes you did:
Closes #3790 
Closes #3791 
Closes #3789 

example: http://localhost:3000/catalogue_demo/ssr-catalogue/testNetwork1/cohorts/testCohort1

how to test:
- setup mail service to given contact ( see docs on email service for catalogue)
- make sure to change/select a cohort contact email to a address that is owned by you ( i.e. do not send 'test' email to 'real' cohorts 
- click the contact button
- fill out the form ( with and without filling in topic field
- check email for message topic should be part of subject and message ( if filled in )

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-06-14 13:37 UTC, EleanorHyde-UMCG commented
I see no topic field in the contact form in 3875 prev...? Just this:

![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/ee445bbf-3bae-4b80-9870-a2357e62bd1d)

2024-06-18 11:27 UTC, chinook25 requested changes
Code looks good, but I don't know how to test it from your h2t:

- Where can I find the docs? It's not in the readme
- Where can I find the contact button? https://preview-emx2-pr-3875.dev.molgenis.org/catalogue-demo/ssr-catalogue/

2024-06-18 11:27 UTC, chinook25 commented on apps/nuxt3-ssr/components/content/ContentBlockIntro.vue
> +  senderName: {
Records are so much better to deal with than arrays <3

2024-06-18 11:27 UTC, chinook25 commented on apps/nuxt3-ssr/components/content/ContentBlockIntro.vue
> +  if (!fields.senderEmail.fieldValue) {
In the constants file of the components lib is a regex for validating email addresses, might be an idea to apply it here?

2024-06-19 08:01 UTC, chinook25 approved these changes

2024-06-19 08:02 UTC, merged