feat: remove aggregates from catalogue model
molgenis/molgenis-emx2 pull request #3924
Opened 2024-06-27 07:47 UTC by BrendaHijmans

What are the main changes you did:
- explain what you changed and essential considerations.

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-07-18 18:01 UTC, mswertz requested changes

2024-07-19 07:08 UTC, aneashodselmans approved these changes

2024-07-19 07:53 UTC, BrendaHijmans commented on data/_models/shared/Aggregates.csv
> +FORCE_NEN patients,,,,,,,,,,,,"Resource counts for e.g. samples, clinical data",DataCatalogueAggregates,
Moved file to specific and deleted profile (specific data models are not included in profiles).

Renamed file to 'Catalogue aggregates'. The plan is to have all aggregate use cases in one data model and deployed on the server in one schema.

2024-07-19 07:55 UTC, BrendaHijmans commented on data/_profiles/DataCatalogueAggregates.yaml
> +profileTags: DataCatalogueAggregates
profile was removed, because specific models do not use profiles

2024-07-19 14:19 UTC, mswertz approved these changes

2024-07-19 14:20 UTC, merged