feat(analytics, ui): event based analytics service plus tailwind UI for the settings
molgenis/molgenis-emx2 pull request #4031
Opened 2024-07-15 08:33 UTC by connoratrug

### Analytics
Allow maintainer (admin) user to setup analytics events. When the enduser of the web interface and executes a certain action ( for example clicks on the 'contact' button) a signal is send to a analytics service ( third party; site-improve, google, .. or emx2 analytics endpoint). The app maintainer (admin ? )should be able to configure which events are send in response to what ui element the user interacts with ( initial 'click' event only). The maintainer should be able to configure these events on a per schema basis. 

What are the main changes you did:
- Add 'Trigger' model to the System schema ( a trigger hold the configuration as defined by the maintainer )
- Create a client module that fetches the triggers configured for a schema and initialises event triggers in the client application ( if necessary it fetches code to handle the triggers, i.e. send the analytics events for a certain ( set of ) provider(s).
- Create a API to c.r.u.d triggers
- Create a ui to  c.r.u.d triggers

### Tailwind (analytics) ui ( pre alpha)
Replace bootstrap emx apps with single tailwind+nuxt app , ssr set to false and ui components though layers ( form tailwind-components module)

What are the main changes you did:
- explain what you changed and essential considerations.

how to test:
- this pr only configures the analytics module the ssr-catalogue app, to test the service using this app 
   - Navigate to the tailwind pre alpa ui -> /apps/ui/#/ 
   - Signin ( if not signed in )
   - Select the schema that contains the tables for the catalogue app 
   - Select 'Analytics' in the main menu
   - Press the 'Add' button
   - Add a new trigger, give the trigger a name , copy a valid css selector ( from the page in the ssr-catalogue app ) into the cssSelector field.
   - Visit the page that contains the selector and 'click' the page element that was setup by the cssSelector
   - You can inspect the console log and the network tab to check the setup has run and the event has been fired.

   - If you have acces to the configured analytics provider ( currently only site-improve ) login to the system and check the event have received ( note: this only works if correct server and analytic-key has been configure in site-improve. you may not have the rights the do so ) 

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-07-15 10:40 UTC, mswertz commented
why don't you use the standard forms for the crud? Just like we do with the 'tasks'?

(ideally of course the tailwind version of that).

2024-07-15 10:52 UTC, mswertz requested changes
I vote 'request changes' because of 'metaStore' and massive code duplication frontend for the crud.

In bootstrap I would use the higher order components. I strongly feel we should do that here too? Btw I might not entirely understand the forms you are making so that might change my mind.

2024-07-15 10:52 UTC, mswertz commented on apps/ui/pages/analytics.vue
> +      <Table>
This is code I would want to use higher order components. I don't want to maintain copies of the code for these kinds of screens multiple times.

In the bootstrap we had 'MolgenisTable' for the table that already has the edit buttons.  
If you must you can use seperate 'RowButtonAdd/Delete/Edit' for the edit dialogues.

2024-07-15 10:52 UTC, mswertz commented on backend/molgenis-emx2-analytics/src/main/java/org/molgenis/emx2/analytics/repository/TriggerRepositoryImpl.java
> +          Row triggerRow =
interestingly I have been playing with idea to extend emx2 Table class to also accept `add(Object)` where the backend would automatically map records to rows.

2024-07-15 10:52 UTC, mswertz commented on backend/molgenis-emx2-analytics/src/main/java/org/molgenis/emx2/analytics/repository/TriggerRepositoryImpl.java
> +          inserted.set(triggerTable.insert(triggerRow));
why don't you insert all these in a batch?

2024-07-21 20:13 UTC, mswertz requested changes

2024-07-21 20:13 UTC, mswertz commented on apps/tailwind-components/pages/DataFetch.other.vue
> +<script setup lang="ts">
ok, I might like this over the client as a pattern but there is much knowledge in the client that we are now duplicating.

2024-07-21 20:13 UTC, mswertz commented on apps/tailwind-components/plugins/floating-vue.ts
> +  vueApp.use(FloatingVue);
would be nice to explain what this does so we understand this plugin

2024-07-21 20:13 UTC, mswertz commented on apps/tailwind-components/server/routes/[schema]/api/trigger.ts
> +  const triggerPreviewLocation = "https://preview-emx2-pr-3946.dev.molgenis.org/"
huh?

2024-07-21 20:13 UTC, mswertz commented on apps/tailwind-components/server/routes/[schema]/api/trigger.ts
> +  console.log("to : ", location);
?

2024-07-21 20:13 UTC, mswertz commented on apps/ui/server/routes/[schema]/api/trigger/[trigger].ts
> +  return proxyRequest(event, location);
I thought this is bad practice to do these proxy? Should redirect maybe?

2024-07-21 20:14 UTC, mswertz commented
> > I vote 'request changes' because of 'metaStore' and massive code duplication frontend for the crud.
> > In bootstrap I would use the higher order components. I strongly feel we should do that here too? Btw I might not entirely understand the forms you are making so that might change my mind.
> 
> could the be a bit more specific on the issues and requested changes ? imo there in only code duplication until we delete molgenis-components module

You should have split this PR.

2024-07-23 14:01 UTC, mswertz commented
ok, first course of action is to extract all changes related to tailwind-components

2024-07-25 10:00 UTC, MaxPostema commented
note: tailwind-components are extracted to a separate pr: #4077

2024-08-12 07:55 UTC, mswertz commented on apps/emx2-analytics/README.md
> +use package manager to install the module '@molgenis/emx2-analytics'
we agree not to publish actually.

2024-08-12 07:56 UTC, mswertz commented on apps/emx2-analytics/package.json
> +  "publishConfig": {
config can stay as long we don't call it.

2024-08-12 07:56 UTC, mswertz commented on apps/emx2-analytics/tsconfig.app.json
> +  "compilerOptions": {
other files also have this.

2024-08-12 07:57 UTC, mswertz commented on apps/emx2-analytics/tsconfig.json
> +  "compilerOptions": {
one for the module and one for the app? we will check

2024-08-12 07:58 UTC, mswertz commented on apps/nuxt3-ssr/nuxt.config.ts
> +      analyticsKey: "1466456",
empty

2024-08-15 08:04 UTC, mswertz approved these changes

2024-08-16 13:02 UTC, merged