feat: cohorts, data sources and variables from nested networks are also included in current network views
molgenis/molgenis-emx2 pull request #4048
Opened 2024-07-16 21:30 UTC by mswertz

closes https://github.com/molgenis/GCC/issues/521

What are the main changes you did:
- added partOfNetworks refback to get what networks a network is part of
- used that to in graphql queries to include cohorts, variables, data sources in counts and lists

how to test:
- use the networkOfnetworks and compare results before and after; you should see +1 cohorts, variables to be included.

todo:
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-07-17 08:06 UTC, harmbrugge requested changes

2024-07-17 08:06 UTC, harmbrugge commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue
> +    result = {
This filter (the or part at least) is repeated 4 times. Maybe make this a formatted string, if that's a thing in java script.

2024-07-17 10:04 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +  console.log(JSON.stringify(data.Networks));
indeed

2024-07-17 10:06 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +                    { network: { id: { equals: catalogueRouteParam } } },
indeed, this might be the bug. Should be conditional on !='all'

2024-07-17 11:58 UTC, mswertz commented
> please update tests as needed

@EleanorHyde-UMCG can you assign somebody for the test? I will move the PR to 'catalogue' team

2024-07-17 12:28 UTC, harmbrugge approved these changes

2024-07-17 12:38 UTC, mswertz commented
> Code looks good , 2 small changes / checks requested, and a test is needed for regression. On the model side i'm a bit worried about the number of checks and joins needed for basis functions might be a sign of issue in the way the domain is modelled.
> 
> * see comments
> * add test

Agree on model but I think it is as simple as we can.
Test is an interesting one. I would like @EleanorHyde-UMCG to add an acceptance test and we can add e2e tests. How can I do that most easily?

2024-07-17 12:51 UTC, EleanorHyde-UMCG commented
First of all could someone (@mswertz?) please confirm that the following is a correct description of the query?

_All variables in a network-of-networks are: all the variables in all the CDMs which have been designated as belonging to the networks hanging under the network-of-networks in question PLUS any variables which have been designated as specifically belonging to the network-of-networks (for whatever reason).  With duplicates removed._

2024-07-18 08:48 UTC, BrendaHijmans requested changes
Functional review: variable counts are correct but link to variable harmonisation details is broken in variables in nested network. To test, upload this zip in catalogue-demo schema on preview: 
[catalogue-demo1721292572235.zip](https://github.com/user-attachments/files/16280345/catalogue-demo1721292572235.zip)
Go to EHEN network, click on vaiables, click on a variable, get an empty blue screen.

2024-07-18 17:18 UTC, mswertz commented on data/_models/shared/DataCatalogue-TODO.csv
done

2024-07-18 19:15 UTC, mswertz commented on apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
> +                    { network: { id: { equals: catalogueRouteParam } } },
this is a 'scoped' block

2024-07-19 10:29 UTC, BrendaHijmans requested changes
The variable count on the network homepage is not correct. Upload this excel in catalogue_demo to test: 
[var_counts_test.xlsx](https://github.com/user-attachments/files/16310762/var_counts_test.xlsx). Go to TESTNETWORK in ssr to test. Variable count should be 25 (10 from test1, 10 from test3 and 5 from test2 via Network variables). Also, the link to variable details is broken. See pictures for discrepancy in counts, counts on hompepage are not correct, but list count is.
![image](https://github.com/user-attachments/assets/5d95539d-1684-4a64-85e1-f2f14dc1ea44)
![image](https://github.com/user-attachments/assets/261f7dc1-29a5-44b0-aa2f-9d983f913605)

2024-07-21 21:34 UTC, mswertz commented
> code looks good , please remove console.log statements

done

2024-07-23 06:55 UTC, mswertz commented
> The variable count on the network homepage is not correct. Upload this excel in catalogue_demo to test:
> [var_counts_test.xlsx](https://github.com/user-attachments/files/16310762/var_counts_test.xlsx). Go to TESTNETWORK in ssr to test.

fixed. Turned out that this network has no cohorts and thus no mappings. Added check for empty cohorts list.

2024-07-23 09:50 UTC, merged