feat (components): add catalogue components to tailwind component lib
molgenis/molgenis-emx2 pull request #4077
Opened 2024-07-25 09:55 UTC by MaxPostema

What are the main changes you did:
- extracted tailwind components from #4031

how to test:
- alle the new components work
 
todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-08-08 17:47 UTC, davidruvolo51 requested changes
Overall, everything looks good. There are some minor things: types missing, lang tags missing, moving CSS computed to tailwind, etc. There are also some larger questions about merging components, rewriting them, etc.

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/content/type/ContentTypeRefBack.vue
> +          row.find((col: any) => col.key === longestRowColumns.key)?.value
is the type for `col` a `Record`?

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/content/type/ContentTypeString.vue
> +import type { ISectionField } from "~/interfaces/types";
Is this file available? To organise the files, should we use interfaces or types?

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/content/type/ContentTypeText.vue
> +import type { ISectionField } from "~/interfaces/types";
Same as the previous comments

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/display/List.vue
> +      :class="`${columnCountClass} ${listClasses} `"
The JS code should be moved in into the class attribute

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/display/ListItem.vue
> +  <li :class="listItemClasses"><slot></slot></li>
If possible, the css classes should be defined inline

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DataFetch.other.vue
> +    <h3 class="text-heading-lg">Params</h3>
This should be a `h2` element

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DataFetch.other.vue
> +      <label for="table-id-select">table id: </label>
Is this component used more than once? If so, we need to autogenerate the identifiers

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DataFetch.other.vue
> +  <div v-if="metadata">
I think the headings need to be revised. I need to see this in action first.

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DisplayList.story.vue
> +const columnCount = ref(1);
Missing type `number`

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DisplayList.story.vue
> +const numberOfDemoItems = ref(3);
Missing type

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/DisplayList.story.vue
> +const type: Ref<"standard" | "link"> = ref("standard");
Should we type variables using the `const var: Ref<...>` approach or using `const var = ref<...>()`?

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/FilterSearch.story.vue
> +const searchValue = ref("");
Typing is missing

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/content/ContentBlock.vue
> +    <h2 class="mb-5 uppercase text-heading-4xl font-display" v-if="title">
I'm assuming that this component isn't used as a subsection. If see, we would need to make the heading element more flexible.

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/FooterComponent.vue
> +        github </a
There's an extra space in there. In the browser, it returns `( github )`

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/LogoMobile.vue
I feel like this component could be combined with the Logo component. The logo component could be smatter to show/hide elements based on screen width.

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/Modal.story.vue
> +let sectionCount = ref(0);
Missing type `number`

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/Table.story.vue
This story does not appear in the showcase

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/components/content/ContentReadMore.vue
The button labels aren't semantic. They should probably say "read more" / "read less". If it is preferred to use the ellipsis, then we should add a label that is visually hidden.

```vue
<button>
    ...
   <span class="sr-only">show more</span>
</button>
```

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/content/ContentGenericItemList.story.vue
This story isn't visible. Maybe I'm missing something?

2024-08-08 17:47 UTC, davidruvolo51 commented on apps/tailwind-components/pages/content/ContentBlocks.story.vue
The story isn't shown in the showcase.

2024-08-13 12:49 UTC, MaxPostema commented on apps/tailwind-components/components/TableCell.vue
> +    <div :class="{ 'whitespace-nowrap': allowLineBreak }"><slot></slot></div>
I don't think it's against the html5 standard? What would be your alternative suggestion?

2024-08-13 12:51 UTC, MaxPostema commented on apps/tailwind-components/components/TableCell.vue
> +  <td
Good idea, but lets say that is out of scope of a 'moving-components' PR

2024-08-13 14:05 UTC, MaxPostema commented on apps/tailwind-components/components/Button.vue
> +    :class="`${colorClasses} ${sizeClasses} ${iconPositionClass} transition-colors`"
I think the whole button will need a good iteration on its self. Lets not do this in this PR.

2024-09-13 07:46 UTC, closed without merging