feat(central): show progress when uploading data csv files
molgenis/molgenis-emx2 pull request #4115
Opened 2024-08-06 12:49 UTC by harmbrugge

#3059 

What are the main changes you did:
- The CsvApi wil progress a post request async as a Task instead
- Updated the front-end accordingly.

how to test:
- Upload any data from a csv file into a table.

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-08-07 08:05 UTC, mswertz requested changes
Add junit test to get coverage over 80% (actually sonar should have failed).
I think if you would add a one liner for the ?async=true in WebApiSmokeTests you would cover all java code.

You can see here what code is not covered
https://sonarcloud.io/component_measures?id=molgenis_molgenis-emx2&pullRequest=4115&metric=new_coverage&view=list

2024-08-07 11:47 UTC, mswertz approved these changes

2024-08-07 15:04 UTC, davidruvolo51 commented
I performed a functional review of the csv import. I noticed a couple of issues. 

## Import does not timeout or show errors

I created a test dataset for the pet store and tried to import it. While I see the nice import display, the progress does not update. I don't see any errors or updates regarding the import. In the dev console, I see that the graphql requests are executing fine, but the response is the same:

```
{
  "data" : {
    "_tasks" : [
      {
        "id" : "e4ae8c38-ad8e-4626-b55c-b61e2a8aa852",
        "description" : "Importing rows into Pet for 321604ms",
        "status" : "RUNNING",
        "subTasks" : [ ]
      }
    ]
  }
}
```

To reproduce this issue -

1. Sign in as admin
2. Go to up/download page in the pet store
3. Import this csv file [Pet.csv](https://github.com/user-attachments/files/16530459/Pet.csv)

## The progress indicator isn't shown when importing a `molgenis.csv` file

When importing a `molgenis.csv` file, the progress indicator is not display.

1. Create a new schema
2. Import the following csv file: [molgenis.csv](https://github.com/user-attachments/files/16530527/molgenis.csv)

2024-08-08 07:24 UTC, davidruvolo51 approved these changes
Looks good! I have one comment regarding the structure of the fetch. Otherwise, everything works fine.

2024-08-08 07:24 UTC, davidruvolo51 commented on apps/updownload/src/components/Import.vue
> +                response.json().then((response) => {
More of a preference really, but in the `response.ok` check can also return `response.json()` and pass it to another `then`.

```
fetch(...)
.then((response) => {
    if (response.ok) {
       return response.json()
    }
  ...
})
.then((result) => {
   // process the response here
})
.catch((err) => {
   // handle error here
})
```

2024-08-08 08:01 UTC, chinook25 commented on apps/updownload/src/components/Import.vue
> +                    // if identifier is present it's a task
Try to not add comments like these, if you really want to make the code more clear use functions/variable names. Here you could do `if (isTask(response))`.

2024-08-08 08:02 UTC, chinook25 commented on backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/CsvApi.java
> +    if (fileNameMatchesTable) { // so we assume it isn't meta data
metadata is one word

2024-08-08 11:44 UTC, merged