feat(central): only fetch changelog on user request
molgenis/molgenis-emx2 pull request #4141
Opened 2024-08-16 10:08 UTC by connoratrug

What are the main changes you did:
- Not all admin / manager user want to see the changelog ( last updated schema ) all the time as it takes some time to query this for all the schema's. This pr places the data request behind a button 

how to test:
- Not admin or manger , nothing changes , no btn is shown
- as admin or manger by default no change log data is shown ( fetched ) , but a btn is shown to request the data
- if the btn is clicked the data is fetched 

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-08-16 11:41 UTC, YpeZ commented
I like it. Works very smoothly. Couple of comments

- I added an entry in a table in each schema. When clicking the button, I can see that queries are launched, but the cells are not populated
- The spacing looks a bit awkward at the moment, but I suppose that's low priority

2024-08-16 12:19 UTC, YpeZ commented on apps/central/src/components/Groups.vue
> +        >Hide Changelog</ButtonOutline
Change to `Hide changelog`, no capital `C`, same in line 27

2024-08-19 09:37 UTC, chinook25 requested changes

2024-08-19 09:37 UTC, chinook25 commented on apps/central/src/components/Groups.vue
> +      >
Layout of the <> brackets is ugly, could you change it to:
<tag>
  content
</tag>
?

2024-08-19 09:37 UTC, chinook25 commented on apps/central/src/components/Groups.vue
> +    showChangeColumn: function (val) {
usually we use the ()=>{} style function in the watches, why this time function(){} ?

2024-08-19 09:37 UTC, chinook25 commented on apps/central/src/components/Groups.vue
>              this.fetchChangelogStatus();
if showChangeColumn is initially false and is changed to true later, doesn't the fetchChangeLogStatus also need to happen? Does this if need to be moved to the watch?

2024-08-19 10:03 UTC, chinook25 approved these changes

2024-08-19 11:04 UTC, merged