feat(directory): biobank services as a separate entity
molgenis/molgenis-emx2 pull request #4155
Opened 2024-08-22 05:09 UTC by dtroelofsprins

What are the main changes you did:
- Removed the capabilities column from the biobanks table
- Added a services column to the biobanks table
- Created a new services table with the column provided the document in https://github.com/molgenis/GCC/issues/554
- Added some dummy services data (for the moment one row)
- Removed the capabilities ontology table

how to test:
- Goto the preview and check the directory-demo (or create a new schema using the biobank_directory template) and see that it includes a services table which is linked to the biobanks table

todo:
- [ ] updated docs in case of new feature => Datamanager Manual needs to be adjusted
- [x] added/updated tests
- [nvt] added/updated testplan to include a test for this fix, including ref to bug using # notation
- If first round of review is OK:
- [ ] Add services table also to the staging area template
- [ ] Adjust the Directory app as it's not working properly anymore (#3770)

2024-08-29 09:04 UTC, esthervanenckevort requested changes
In general the change is consistent with the proposal. I would model TRL as an ontology item. 
I do realize by seeing how things are filled in that searching for services will become much harder, so that is something we need to discuss in the working group. For now I would like to keep this on a separate branch and not yet implement frontend changes.

2024-08-29 09:04 UTC, esthervanenckevort commented on data/biobank-directory/molgenis.csv
> +Services,,tRL,Technology Readiness Level ,string,,false,,"Technology Readiness Level - concept for self-assessment of the service, used in some European projects (https://en.wikipedia.org/wiki/Techno
I would use the list from wikipedia as an ontology. Would make things easier to understand for user.

2024-08-29 09:18 UTC, esthervanenckevort commented on data/biobank-directory/molgenis.csv
> +Services,,tRL,Technology Readiness Level ,string,,false,,"Technology Readiness Level - concept for self-assessment of the service, used in some European projects (https://en.wikipedia.org/wiki/Techno
I think we should also add a ref_array to an service type ontology, like in this presentation:
https://docs.google.com/presentation/d/1YehXQMGbTVwH_zJbrxW7eVqj1E5QMvtt/edit#slide=id.p4
(Slide 4)
That would make it possible to search for services that offer a specific type of service (e.g. DNA analysis service)

2024-08-30 11:58 UTC, esthervanenckevort reviewed
Zo ziet het er beter uit. Voordat we eventueel mergen ga ik dit bespreken met de MIABIS werkgroep (afspraak op dinsdag)

2024-11-12 08:06 UTC, esthervanenckevort requested changes
Paar punten:
- In het data model staat nog een opmerking over de service types: de parents mogen niet geselecteerd kunnen worden.
- In de services lijst stonden een aantal spellingsfouten zoals nucleis acid ipv nucleic acid. Ik heb die in de lijst gecorrigeerd.
- De quality attributen worden ook hiervoor weer door BBMRI-ERIC quality team beheert dus afwijkend van het model moet dat een externe data structuur zijn, net zoals de biobank en collection quality info. Ik zag dat de opmerking hierover in het model was weggehaald door Andrzej dus dat was niet duidelijk.

2024-11-13 05:55 UTC, dtroelofsprins commented
> Paar punten:
> 

> > * In het data model staat nog een opmerking over de service types: de parents mogen niet geselecteerd kunnen worden.

=> Dan kunnen deze niet in de parents kolom, ik heb nu een aparte kolom serviceCategory (string) toegevoegd. Of moet dit eventueel een ontology naar een aparte ontology table ServiceCategories worden?
Overigens heb ik paar keer door het document heen gekeken, maar ik kan nergens deze opmerking vinden?

> > * In de services lijst stonden een aantal spellingsfouten zoals nucleis acid ipv nucleic acid. Ik heb die in de lijst gecorrigeerd.

=> Aangepast, ik had er zelf een klein typfoutje uitgehaald, vond nucleis idd ook al raar en er was nog eentje, maar ik dacht zal wel goed zijn als het zo is aangeleverd...

> > * De quality attributen worden ook hiervoor weer door BBMRI-ERIC quality team beheert dus afwijkend van het model moet dat een externe data structuur zijn, net zoals de biobank en collection quality info. Ik zag dat de opmerking hierover in het model was weggehaald door Andrzej dus dat was niet duidelijk.

=> Aparte QualityInformationServices tabel aangemaakt, met refback in Services naar deze tabel.

2024-11-13 08:16 UTC, esthervanenckevort requested changes
- In de service types tabel zijn de labels inconsistent. Die zouden allemaal de human readable tekst moeten zijn, dus niet de woorden met koppelstreepjes verbonden maar met spaties en hoofdletters voor de eerste letter van zelfstandige naamwoorden.
- Ik denk dat het beter is om de service categories als een aparte tabel te modelleren.

2024-11-14 09:18 UTC, esthervanenckevort approved these changes

2024-11-14 10:27 UTC, merged