chore(emx2): spark to javalin migration
molgenis/molgenis-emx2 pull request #4165
Opened 2024-08-26 19:57 UTC by harmbrugge

What are the main changes you did:
- explain what you changed and essential considerations.

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-09-19 06:19 UTC, dtroelofsprins requested changes
Did some functional tests:
Successful:
- [x] Create Directory schema from template including demo data
- [x] Schema editor 
- [x] DataCatalogueTemplate 
- [x] Fair data hub template
- [x] Data upload (zipfile with several csv's) using UI
- [ ] Other templates STILL NEED TO BE TESTED 

Not working properly:
- [ ] Create ERN Dashboard from template when going to the schema a white screen is shown, should go to /tables/#
- [ ] Directory App => footer is broken, pictures not shown (f.e. logo)
- [ ] Manually adding data => FAILS WITH ERROR: `Parsing of graphql variables failed. Should be an object with each graphql variable a key. argument "content" is null: argument "content" is null`
- [ ] Manually updating data => FAILS WITH ERROR `Parsing of graphql variables failed. Should be an object with each graphql variable a key. argument "content" is null: argument "content" is null`
- [ ] Run a script on the server => Cannot create a script due to saving error (Running the hello world script works)
- [ ] Run a script locally using the EMX2-pyclient => 
    -  create schema using template WORKS
    - downloading real BBMRI-ERIC biobanks fails with error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 8688: invalid continuation byte` => using the same script, with the same data on emx2.dev.molgenis.org works fine.

2024-09-23 11:46 UTC, dtroelofsprins requested changes
Did some functional tests:
Successful:
- [x] Create Directory schema from template including demo data
- [x] Schema editor 
- [x] Use DataCatalogueTemplate 
- [x] Fair data hub template
- [x] Data upload (zipfile with several csv's) using UI
- [x] Other templates => tested several, but not all
- [x] Schedule a script
- [ ] Failure email when script fails => NOT POSSIBLE on preview server 

Fixed:
- [x] Directory App => footer is broken, pictures not shown (f.e. logo)
- [x] Manually adding data
- [x] Manually updating data
- [x] Create ERN Dashboard from template when going to the schema a white screen is shown, should go to /tables/#
- [x] Run a script on the server
- [x] Run a script locally using the EMX2-pyclient => 
    -  create schema using template WORKS
    -  downloading real BBMRI-ERIC biobanks

New issues (probably not tested before):
- Directory App => Load json settings does not have the proper layout
- CatalogueTemplate => SSR Catalogue shows white screen => Might also be due to recent changes to the catalogue that it's not working properly

2024-09-30 10:20 UTC, mswertz reviewed
looks good.
I tested:
* catalogue app
* simple form and explorer using pet store
* set theme to use another color
* viewed a sql report

2024-09-30 10:20 UTC, mswertz commented on backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPoint.java
> +  public FAIRDataPoint(Context ctx, Schema... schemas) {
For another time: fair data point should not need ctx but instead return something that the service can render
(in other words: this molgenis-emx2-fairdatapoint package should now know about javalin(

2024-09-30 10:20 UTC, mswertz commented on backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java
> -  private void createCustomJettyServerFactoryWithCustomSessionListener() {
this is not needed anymore? That is great!

2024-09-30 10:21 UTC, mswertz approved these changes
looks good.
I tested:
* catalogue app
* simple form and explorer using pet store
* set theme to use another color
* viewed a sql report

2024-10-02 09:09 UTC, harmbrugge commented
> go to https://preview-emx2-pr-4165.dev.molgenis.org/apps/ui/#/ select a schema reload page: 'File not found' error same issue for sub pages

Should be fixed now

2024-10-04 05:31 UTC, dtroelofsprins commented
> Did some functional tests: Successful:
> 
> * [x]  Create Directory schema from template including demo data
> * [x]  Schema editor
> * [x]  Use DataCatalogueTemplate
> * [x]  Fair data hub template
> * [x]  Data upload (zipfile with several csv's) using UI
> * [x]  Other templates => tested several, but not all
> * [x]  Schedule a script
> * [ ]  Failure email when script fails => NOT POSSIBLE on preview server
> 
> Fixed:
> 
> * [x]  Directory App => footer is broken, pictures not shown (f.e. logo)
> * [x]  Manually adding data
> * [x]  Manually updating data
> * [x]  Create ERN Dashboard from template when going to the schema a white screen is shown, should go to /tables/#
> * [x]  Run a script on the server
> * [x]  Run a script locally using the EMX2-pyclient =>
>   
>   * create schema using template WORKS
>   * downloading real BBMRI-ERIC biobanks
> 
> New issues (probably not tested before):
> 
> * Directory App => Load json settings does not have the proper layout
> * CatalogueTemplate => SSR Catalogue shows white screen => Might also be due to recent changes to the catalogue that it's not working properly

From these two new issues, the first one, loading the JSON settings in the Directory App is still not working OK.
Second thing: It seems the refback fix that Morris merged last week is not included in here? As creating a schema with Directory template takes a whole lot longer than it currently does in production.

2024-10-04 09:26 UTC, esthervanenckevort submitted a review, later dismissed
- Should update with master and resolve merge conflicts.
- There is some inconsistency in using static function call vs instance method calls, but I don't see this as a blocking issue since the code does work and part of that issue was already in the existing code base.

Directory app works
Catalogue (old app) gives error. Probably not related to this PR, but to the data model changes
SSR catalogue seems to work fine
Table explorer, editing of data and downloads in different formats work

2024-10-08 10:03 UTC, merged