fix(molgenis-components): fixed a bug causing null-check for form expressions to fail
molgenis/molgenis-emx2 pull request #4189
Opened 2024-09-05 17:00 UTC by svandenhoek

What are the main changes you did:
Fixed a bug where empty value validation was bugged. Once a field is filled, it cannot be put back into its original (`value is null`) state. Similar to https://github.com/molgenis/molgenis-emx2/pull/3933.

Example:

https://github.com/user-attachments/assets/da339354-ac8d-41db-b77f-5e0aaa3d5740

To be more specific, if having a table with 2 columns (`c1` & `c2`), where `c2` can only be filled if `c1` is empty, different code would give different errors:

`c1 == null` -> only worked as long as `c1` is empty, if filled and emptied again the error message would remain
`c1.length === 0` -> only worked AFTER value was set and then emptied, but when trying to save give the error `Update into table 'test' failed.: Transaction failed: script failed: TypeError: Cannot read property 'length' of null`
`c1 == null || c1.length === 0` -> works but ugly

**This PR should address the issue above and make `<colName> == null` always usable. It fixes InputString, InputText, InputEmail, InputHyperlink & InputPassword.**

Only `InputString` was tested manually with validation string in an actual database table. Other ones have e2e tests to see if value is set to `null` if empty input field.

how to test:
- When creating a `validation` for a column, `<colName> == null` should now work correctly. F.e. http://localhost:8080/apps/molgenis-components/#/component/InputString and checking if `value` is removed (`null`) when field is empty.

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-09-09 09:59 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputEmail.vue
> +  emit("update:modelValue", value == "" ? null : value);
Please use === instead of ==

2024-09-09 10:00 UTC, chinook25 commented on apps/molgenis-components/src/components/forms/InputHyperlink.vue
> +
Please put functions at the end of the script

2024-09-30 09:16 UTC, svandenhoek commented
Included `InputSelect` from https://github.com/molgenis/molgenis-emx2/pull/3933 while processing the feedback.

2024-10-11 08:10 UTC, chinook25 requested changes
see comment

2024-10-11 08:10 UTC, chinook25 commented on apps/molgenis-components/src/components/utils.ts
> +export function updateModelValueEmit(emit, value) {
- These contain ts errors (implicit any type). Do you have your IDE setup correctly? It should show red lines on these functions.
- Is it possible to pass this.$emit into the second function? In that case we could remove the first.
- This comment should not be here, comments double the maintenance of code so should be used only if really necessary.
- I suggest renaming the function to better reflect what they do e.g. `emitModelValueNullSafe`

2024-10-14 10:36 UTC, closed without merging

2024-10-14 10:36 UTC, svandenhoek commented
This PR is closed in favor of #4353