chore: docs to 4.0
molgenis/molgenis-emx2 pull request #4243
Opened 2024-09-20 19:53 UTC by BrendaHijmans

What are the main changes you did:
- explain what you changed and essential considerations.

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-10-07 13:38 UTC, EleanorHyde-UMCG approved these changes

2024-10-07 14:23 UTC, hslh commented on docs/catalogue/cat_cohort-data-manager.md
> +- The metadata of cohorts include descriptive information such as contact details, name of the resource, and a high-level
'The metadata of cohorts' -> 'The metadata of resources'/'The metadata of data resources'

2024-10-07 14:33 UTC, hslh commented on docs/catalogue/cat_network-data-manager.md
> +- The resource metadata provides descriptive information such as contact details, name of the cohort, and high-level
'name of the cohort' -> 'name of the resource'

2024-10-08 09:52 UTC, timcadman requested changes
Just made a few suggestions on the English but otherwise looks good :)

2024-10-08 09:52 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +framework to describe in detail: metadata of different data resources, such as cohorts and data sources; definitions of
I would probably say "... data resources (such as cohorts and data sources); ..."

2024-10-08 09:52 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +[Fortier et al, 2017](https://pubmed.ncbi.nlm.nih.gov/27272186/) and multi-data source studies
datasource?

2024-10-08 09:52 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +LongITools. You will need login details to upload metadata to MOLGENIS catalogue.
"the MOLGENIS catalogue"

2024-10-08 09:52 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +consists of multiple sheets. Each sheet corresponds to a table in catalogue. The columns in the sheet
"the catalogue"

2024-10-08 09:52 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +upload the metadata to the catalogue see the section To upload the metadata to the catalogue see the
Something has gone wrong with this sentence!

2024-10-11 15:07 UTC, timcadman approved these changes
Just one more 'the' that needs to be added but happy to approve it

2024-10-11 15:07 UTC, timcadman commented on docs/catalogue/cat_network-data-manager.md
> +LongITools. You will need login details to upload metadata to MOLGENIS catalogue.
Should read 'the' MOLGENIS catalogue

2024-11-07 07:41 UTC, merged