chore: align tailwind tables with ui design
molgenis/molgenis-emx2 pull request #4371
Opened 2024-10-17 08:02 UTC by connoratrug

What are the main changes you did:
- Align tabels page with [design](https://www.figma.com/proto/uSAeYVHKsOIa2BXT7Kx07n/Molgenis-Design?page-id=868%3A1678&node-id=4412-335236&node-type=frame&viewport=26035%2C-8351%2C0.5&t=VWhbD6hYkc8lCC6G-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=4412%3A335236&show-proto-sidebar=1)
- remove content block container 
- add bg color to table 
- add border radius to table
- set margen as per design
- remove debug loading indicator

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-10-17 12:04 UTC, mswertz reviewed
what to do with rounded borders limiting text?
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/0dc072c1-cc95-4b5d-b863-db1c7e73c3bb">

2024-10-17 18:00 UTC, mswertz approved these changes
ok, we solve the issue with rounded corners later

2024-10-18 10:19 UTC, davidruvolo51 requested changes
Looks great!

I added a suggestion the rounded table border and spacing issue in the last row.

2024-10-18 10:19 UTC, davidruvolo51 commented on apps/tailwind-components/components/table/TableEMX2.vue
> +    <div class="overflow-x-auto overscroll-x-contain bg-table rounded-t-3px">
To have enough spacing at the bottom, it's possible to add `pb-*` here. In this design, I noticed that the text hugs the left side of the table. We could consider adding a little bit of space in the first cell in each row.

2024-10-18 10:19 UTC, davidruvolo51 commented on apps/tailwind-components/components/table/TableEMX2.vue
> +        <tbody class="mb-3">
To remove the border from the last row, you can structure the class like this -

```
<tbody class="mb-3 [&_tr:last-child_td]:border-none">
```

I found that the text feels compressed. We could also add a little bit of space on the bottom: 

```
<tbody class="mb-3 [&_tr:last-child_td]:border-none [&_tr:last-child_td]:mb-5">
```

2024-10-29 07:45 UTC, davidruvolo51 approved these changes
Looks good!

2024-11-04 08:19 UTC, merged