feat(catalogue): change Samplesets to Sample collections and update
molgenis/molgenis-emx2 pull request #4375
Opened 2024-10-17 11:38 UTC by hslh

What are the main changes you did:
- renamed table Samplesets to Sample collections and add attributes and ontology tables to make it suitable for mapping the Collections table from the BBMRI-ERIC directory. 

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-10-23 07:55 UTC, BrendaHijmans commented on data/_models/shared/Sample collections.csv
> +Sample collections,,,lowest age unit,ontology,,,CatalogueOntologies,Age units,,,,,,,,,"DataCatalogueFlat,CohortsStaging,RWEStaging,NetworksStaging,StudiesStaging",,"Unit defining lowest age - MIABIS-
We should merge Age units (from BBMRI) and Age groups (from catalogue)

2024-11-28 09:52 UTC, esthervanenckevort requested changes
- Some ontologies can be deduplicated with the existing ontologies
- Should specify codes in ontologies

2024-12-06 10:45 UTC, BrendaHijmans commented
I am not sure why we are not using the Resources table for Sample collections. There are many overlapping attributs between Sample collections and Resources, and the additions can also be used by other resource types. This would also solve adding two identical quality tables: one for biobanks (Resource qualities) and one for Sample collections (Sample collection qualities).

In the cohort domain we use Resources for Networks/Consortia (resource type=Network) and link them via Resources.resources ref_array. 

(Still need to look at details of atributes)

2024-12-16 15:05 UTC, hslh commented
That being said, if we decide that mapping Collections to Resources is the best option after all, that's fine with me, most of the work should be transferable. As long as we don't keep going back-and-forth :)

2025-01-15 09:34 UTC, hslh commented
Collections -> Collection Events? Make a proposal. So now we have three options: Resources/Sample Collections/Collection Events

2025-06-16 07:22 UTC, mswertz approved these changes

2025-06-16 07:23 UTC, mswertz requested changes
oh wait, content looks good but build fails

2026-09-03 12:37 UTC, hslh commented
outdated

2026-09-03 12:37 UTC, closed without merging