fix(central): schema names with - should be allowed
molgenis/molgenis-emx2 pull request #4391
Opened 2024-10-24 06:41 UTC by mswertz

needed because of catalogue-demo schema (cannot now be created via UI while we use it for tests)

2024-10-24 13:03 UTC, chinook25 requested changes
Doesnt work: `test-test` fails. Regex needs to be: `/^(?!.* _|.*_ )[-a-zA-Z][-a-zA-Z0-9 _]{0,30}$`
(another `-` in between the last [])

2024-10-24 13:58 UTC, mswertz commented on apps/central/src/components/SchemaCreateModal.vue
> +      const simpleName = constants.SCHEMA_NAME_REGEX;
I will check, should be check but if missing will add

2024-10-24 13:59 UTC, mswertz commented
> Doesnt work: `test-test` fails. Regex needs to be: `/^(?!.* _|.*_ )[-a-zA-Z][-a-zA-Z0-9 _]{0,30}$` (another `-` in between the last [])

indeed, thx

2024-10-25 07:34 UTC, mswertz commented on apps/central/src/components/SchemaCreateModal.vue
> +      const simpleName = constants.SCHEMA_NAME_REGEX;
added

2024-10-28 11:32 UTC, mswertz commented
> Doesnt work: `test-test` fails. Regex needs to be: `/^(?!.* _|.*_ )[-a-zA-Z][-a-zA-Z0-9 _]{0,30}$` (another `-` in between the last [])

Shouldn't it be `/^(?!.* _|.*_ )[a-zA-Z][-a-zA-Z0-9 _]{0,30}$` to prevent a start with -?

2024-10-28 12:58 UTC, chinook25 commented
> > Doesnt work: `test-test` fails. Regex needs to be: `/^(?!.* _|.*_ )[-a-zA-Z][-a-zA-Z0-9 _]{0,30}$` (another `-` in between the last [])
> 
> Shouldn't it be `/^(?!.* _|.*_ )[a-zA-Z][-a-zA-Z0-9 _]{0,30}$` to prevent a start with -?

If you want to prevent that, yes ;)

2024-10-29 06:14 UTC, merged