feat(central): adjustable menu for apps/central
molgenis/molgenis-emx2 pull request #4401
Opened 2024-10-25 13:25 UTC by connoratrug

adjustable menu for apps/central

Closes #4239

What are the main changes you did:
 - Check setting for menu option at the database level
- Use settings menu if set
- add Admin item if sigined in as admin
- implement key filter for gql settings query at the database level

how to test:
- sign in as admin , go to settings , add a setting at the db level with a key of 'menu' and a value that is a list of menu items 
- view central app , signin/signout as admin

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-10-28 11:20 UTC, mswertz reviewed
so we don't have the 'schema admin' to edit the menu but only the setting, right?

2024-10-28 11:21 UTC, mswertz approved these changes
Approved => lets keep the menu editor widget that we have on schema level for later

2024-10-29 06:38 UTC, dtroelofsprins requested changes
There are a couple of things, I think it's good to have a short meeting about this.

2024-11-05 07:01 UTC, dtroelofsprins approved these changes
- [x] new database => apps/central has default menu items
- [x] new schema => schema menu has default menu items
- [x] apps/central menu can be adjusted
- [x] schema menu's can be adjusted

Also added logoURL and additionalCss to apps/central settings => These are then also visible in any newly created schema, instead of the default schema colours and logo. These can be adjusted via local schema settings (tested this), so not sure if this is really a big issue.

2024-11-06 08:41 UTC, merged