fix: when setting isOidcEnabled is false override env variable
molgenis/molgenis-emx2 pull request #4403
Opened 2024-10-28 13:06 UTC by harmbrugge

What are the main changes you did:
- When the database setting isOidcEnabled is set to false it will used this setting and overrides env OIDC properties

how to test:
- Spin up an instance of emx2 with OIDC env variables set
- See OIDC is enabled 
- Log in with admin
- Set isOidcEnabled to false
- See that OIDC login is disabled

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-11-07 08:28 UTC, esthervanenckevort requested changes
This latest change can leave you in a situation where it is very hard to recover from.
I would do it the other way around. isOidcEnabled only functioning as a override to temporarily disable OIDC without removing the configuration. If there is no OIDC configuration in the environment then the isOidcEnabled flag is removed from the settings database.

2024-11-07 10:53 UTC, mswertz commented
> This latest change can leave you in a situation where it is very hard to recover from. I would do it the other way around. isOidcEnabled only functioning as a override to temporarily disable OIDC without removing the configuration. If there is no OIDC configuration in the environment then the isOidcEnabled flag is removed from the settings database.

But that would lead to weird dissapearing if a user made the setting. Issen't that confusing?
Harm and I though we should invest in error logging and then in another story make error visible to UI.

2024-11-15 08:31 UTC, mswertz commented on backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
> +            == null) {
I think we agreed to not do this (my bad). So all OIDC parameters go via ENV except the OidcEnabled=true/false

2024-11-20 08:15 UTC, esthervanenckevort approved these changes
Tested on localhost and I can enable and disable OIDC.

One thing we might consider is to force log out everyone when OIDC is disabled or enabled.

2024-11-20 13:35 UTC, mswertz approved these changes

2024-11-21 08:18 UTC, merged