feat(tasks):  bash script type for script tasks
molgenis/molgenis-emx2 pull request #4412
Opened 2024-10-30 15:07 UTC by harmbrugge

closes [#4293](https://github.com/molgenis/molgenis-emx2/issues/4293)

What are the main changes you did:
-  Added a bash script type for script task to execute bash script directly via scripts

how to test:
- Go to the preview server login as admin and go to Scripts
- create a script with type bash
- Command could be: echo "hello world!"
- execute it

todo:
- [ ] updated docs in case of new feature
- [x] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-10-31 08:43 UTC, erikzwart approved these changes
Functionally tested a simple bash script:

```bash
#!/bin/bash
string="Hello"
```
![afbeelding](https://github.com/user-attachments/assets/886b4b2b-7105-4299-bc23-1c1227c2d3b6)

Which works as intended.

Also tested MOLGENIS_TOKEN:

```bash
#!/bin/bash
echo $MOLGENIS_TOKEN
```
![afbeelding](https://github.com/user-attachments/assets/46a05e2a-eb6f-4921-9506-a54e2ac43004)

Also works.

2024-11-06 08:12 UTC, mswertz requested changes
great feature

Indeed I would also like to see change to enum. 

Furthermore, we should update the UI so users can there also define it.
That might also influence the (not) changing the API signature comment.

(some more work but otherwise this feature is not accessible right?)

2024-11-06 20:52 UTC, mswertz commented on backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/ScriptTask.java
> +    return this;
we follow the 'builder' pattern, see also for other setters.

2024-11-06 20:52 UTC, mswertz commented on backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/ScriptTask.java
> +  private String type;
agreed

2024-11-06 21:01 UTC, mswertz approved these changes

2024-11-07 09:20 UTC, merged