chore: Switch to using nuxt icon module
molgenis/molgenis-emx2 pull request #4493
Opened 2024-11-13 14:44 UTC by connoratrug

closes https://github.com/molgenis/molgenis-emx2/issues/4251

What are the main changes you did:
- setup module in tailwind-components lib
- add molgenis icons to the setup
- add samplepage to view/text icons in playground
- 'fix' the svg's to use current fill
- remove 'old' icons and tooling
- rename custom icon files to follow nuxt/icon name schema ( kebab-case )
- open up icon route via ingress ( for k8, vm's need update of nginx config ⚠️ )
- setup app config for playground, catalogue and ui apps 

- [ ] test local
- [ ] test non ssr playground setup 
- [ ] test ssr app usage setup ( catalogue )

2024-11-13 15:34 UTC, mswertz reviewed
looks good, but I am trying to understand the exact benefits. I see that this library gives accesss to 200,000+ icons, that is great. Will we stop generating the icons? Any other benefits I should understand?

2024-11-14 11:10 UTC, mswertz commented on apps/tailwind-components/pages/Button.story.vue
> +        icon="line-md:chevron-small-down"
there is not, it is growing on me. It is just very long names but if we would care very much we could make a mapping list. I don't care for now. Better stick to something documented elsewhere

2024-11-18 13:43 UTC, davidruvolo51 requested changes
This is really great! I noticed one issue in the story and I had a few comments. Otherwise, everything looks great!

2024-11-19 08:35 UTC, mswertz reviewed
Does this close the door for non-nuxt based use of tailwind components?
(or was that door closed already?)

2024-11-19 08:35 UTC, mswertz commented on apps/tailwind-components/README.md
> +The custom (default) icons used in the component library are stored in the assets/icons folder
anything special one needs to do to these icons?

2024-11-21 14:33 UTC, davidruvolo51 approved these changes

2024-11-21 14:33 UTC, davidruvolo51 commented on apps/tailwind-components/assets/icons/completed.svg
Wow! It surprises me that the dimensions are so large.

2024-11-29 15:09 UTC, closed without merging