Feat(dashboards): connect CRANIO dashboard to the database
molgenis/molgenis-emx2 pull request #4516
Opened 2024-11-25 12:28 UTC by davidruvolo51

### What are the main changes you did

In the current version of the `cranio-provider` vue app, the charts are rendered using randomised datasets that are generated on page load. This PR introduces the "live data feed" for these dashboards.

- [ ] Create new ERN_DASHBOARD model that bundles datasets into charts and pages
- [ ] Page "Your Center"
    - [ ] Connect total number of patients submitted to a report or row in the "Charts data" table
    - [ ] The chart "patients by workstream" is live
    - [ ] The chart "patients by workstream and sex" is live
- [ ] Craniosynostosis
    - [ ] All Centers
        - [ ] General overview
            - [ ] Year of birth filter is generated using age groups (e.g., 0-2, 2-4, etc.)
            - [ ] "Type of Craniosynostosis" chart is live and responds to filter
            - [ ] "Affected suture" chart is live and responds to filter
            - [ ] "Multiple suture synostosis" chart is live and responds to age group filter and clicked affected suture
            - [ ] "Patients by country of residence" chart is live. (**NOTE**: Is this chart linked to the filter?)
        - [ ] Surgical Overview
    - [ ] Your center
- [ ] Cleft lip and palate 

### How to test
- explain here what to do to test this (or point to unit tests)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2025-01-15 09:25 UTC, chinook25 requested changes

2025-01-15 09:25 UTC, chinook25 commented on apps/cranio-provider/src/views/provider-cs-all-surgical.vue
> +  (surgeryAgeChart.value as ICharts).yAxisMaxValue = chartAxis.limit;
I see a lot of 'as ...' like this one. I feel like this should not be necessary as the ref is typed. Am I missing something?

2025-01-15 09:25 UTC, chinook25 commented on apps/cranio-provider/tests/index.test.ts
> +test("data is transformed into an object of key-value pairs", () => {
Wrap each different function you test in a 'describe("functionName",()=>{...tests...});'

2025-01-15 09:25 UTC, chinook25 commented on apps/cranio-provider/tsconfig.json
> +    // "allowJs": true,
can be removed? :D

2025-01-15 13:24 UTC, davidruvolo51 commented on apps/cranio-provider/src/types/index.ts
> +export interface ISettings {
Ah, yes. Good point. Overall, the types in the dashboards need to be synced with the tailwind components. I'm planning to update that when we migrate the dashboards to tailwind.

2025-01-15 13:55 UTC, davidruvolo51 commented on apps/cranio-provider/src/views/provider-clp-all-centers.vue
> +  // @ts-expect-error
It's the same, but it might be better to be explicit. This would say that we know there is an error rather than ignoring it.

2025-01-17 12:35 UTC, davidruvolo51 commented on apps/cranio-provider/src/views/provider-clp-all-centers.vue
> +      }
I need to save this for now. There was some talk about adding additional filters. I've rewrite this later.

2025-01-20 08:59 UTC, chinook25 approved these changes

2025-01-27 08:16 UTC, merged