feat(Pyclient): add support for GraphQL API to 'get' method
molgenis/molgenis-emx2 pull request #4558
Opened 2024-12-11 15:49 UTC by YpeZ

### What are the main changes you did
- explain what you changed and essential considerations.

### How to test
- explain here what to do to test this (or point to unit tests)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-12-18 14:40 UTC, YpeZ commented
In my latest commit I implemented a filter on the columns of the output of `get`, i.e. get me the values of only these column of the table.
This leads to discrepancies between the results of the GraphQL and CSV API, as the columns of a table from the GraphQL API and the CSV API may differ.  In my GraphQL query building I include REFBACKs whereas the CSV API does not.

This and my expectation that the implementation of the `query_filter` for GraphQL will differ significantly from the CSV one makes me consider separating these methods into a method for each API, as for the user the arguments they fill in for either format will differ significantly.

2025-01-21 07:13 UTC, dtroelofsprins requested changes
### Code review:
- [x] Looks good and makes sense

### Functional tests:
**Truncate table**
- [x] Truncate table works fine
- [x] Reference from other table => Referenced by Exception

**Get as_df = False or not included NOT APPROVED:**
- ref/ontology column values are not returned as 'country': 'US', but as 'country':  {'name': 'US'}. This is very inconvenient and for sure will break existing scripts.
- Get from an empty table returns a NoneType, where I would expect an empty list with len = 0
- Tested with biobank_directory template (with demo-data), not able to fetch from Collections and CollectionFacts: Table with id 'DiseaseTypes' not found in schema 'DieuwkesTest' => DiseaseTypes is in another schema, but not referenced as an ontology, but as a ref. F.e. Biobanks has also refs to other schema, but these are all real ontologies and this table can be fetched.
- Datatypes: bools go fine
- string type columns with decimal value with zero at the end go fine
- Empty columns are not returned (which is OK)

**Get as_df = True:**
- [x] Retrieve data from an empty tables returns and empty dataframe with len=0
- [x] dataTypes => NaN in bool type columns are filled with True
- [ ] string type columns with decimal value with zero at the end still zero removed if there are no missing values in the column

**Get limited amount of columns**
- [x] as_df = True => nice filter on duplicates
- [x] as_df = False => doesn't filter on duplicates, which is fine I guess

2025-01-31 07:16 UTC, dtroelofsprins requested changes
Remaining from first review:

- [x] Truncate still works fine

**Get as_df = True:**
- [x] dataTypes => NaN in bool type columns should be left empty now they are filled with True => SOLVED
- [x] string type columns with decimal value with zero at the end still zero removed if there are no missing values in the column => SOLVED
- [x] nested filter with list of strings works

**Get as_df = False or not included:**
- [ ] ref/ontology column values are not returned as 'country': 'US', but as 'country':  {'name': 'US'}. This is very inconvenient and for sure will break existing scripts => It seems to be solved for ONTOLOGIES (?), however 'normal' references are still shown as dict: 'contact': {'id': 'bbmri-eric:contactID:NL_1234'}
- [x] Get from an empty table returns a NoneType, where I would expect an empty list with len = 0 => SOLVED
- [x] Can retrieve data from tables with REF to another schema
- [x] nested filter with list of strings works

2025-02-07 09:57 UTC, dtroelofsprins approved these changes
##Final checks
=> separate method for get using GraphQL API
=> as_df = False, just as it was so to_dict from CSV API including the fixes for datatypes, nested filter with list of strings
=> truncate table
=> column selection

### Functional tests:
**Truncate table**
- [x] Truncate table works fine
- [x] Reference from other table => Referenced by Exception

**Get as_df = False:**
- [x] Nested filter with list of strings
- [x] Datatypes: bools go fine => Only EMPTY is treated same as FALSE!!
- [x] string type columns with decimal value with zero at the end go fine

**Get as_df = True:**
- [x] dataTypes
- [x] string type columns with decimal value with zero at the end goes fine

**Get limited amount of columns**
- [x] as_df = True => nice filter on duplicates
- [x] as_df = False => nice filter on duplicates

2025-02-07 11:07 UTC, dtroelofsprins commented on tools/pyclient/README.md
> +#### 11.42.3
This still needs to be adjusted, both version number (there is a more recent version available on pypi) as well as the changes.

2025-02-10 13:50 UTC, YpeZ commented on docs/molgenis/use_usingpyclient.md
> +Retrieves data from a table on a schema using the GraphQL API and returns the result either as a list of dictionaries.
_either_ was left by mistake indeed

2025-02-10 13:58 UTC, merged