feat(directory): Add front page categories
molgenis/molgenis-emx2 pull request #4560
Opened 2024-12-12 12:58 UTC by connoratrug

### What are the main changes you did
- added images 
- add card component
- replace current with image-cards 

note: to test, enable frontpage by setting initialLandingpage.enabled to true 

### Todo 
- [x] add links/ actions, ie what happens when a user clicks a cards 
- [ ] ~link to config, tie to or extend some/all stuff to config~ ( can be separate pr if needed )
- [x] add test

### How to test
- explain here what to do to test this (or point to unit tests)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-12-16 10:48 UTC, esthervanenckevort reviewed
Het gaat de goede richting op, maar er is iets waar ik niet helemaal mijn vinger op kan leggen wat waardoor het er nog niet optimaal uitziet. Ik denk dat het komt omdat de afbeeldingen en de tekst behoorlijk groot zijn in vergelijking tot het voorbeeld in het ontwerp document. Ook is de ruimte tussen de afbeeldingen best groot.
Als ik de grootte van het window aanpas dan komen de afbeeldingen soms over elkaar heen te staan.

2024-12-16 10:48 UTC, esthervanenckevort commented on apps/directory/src/views/Landingpage.vue
> +          <p>pr proceed to the directory without any selection</p>
Typo pr should be or

2024-12-16 14:43 UTC, esthervanenckevort submitted a review, later dismissed
_Functioneel werkt het, maar visueel is het nog behoorlijk dominant en zwaar.
- Ik denk dat het mooier is als er minder nadrukkelijk een rand om de afbeeldingen zijn en er wat meer afbeeldingen op een regel zodat de afstand tussen twee afbeeldingen kleiner is. 
- Ook de tekst erboven mag wat minder nadruk hebben, een h3 ipv h1 vind ik zelf al mooier.
- BBMRI-ERIC is volledig in hoofdletters
- De tekst "Search the BBMRI-ERIC Directory by biobank, samples and collections" is incorrect, dat zou moeten zijn "Search the BBMRI-ERIC Directory by category"

Ik heb even wat met de web inspector gespeeld om de CSS on the fly aan te passen, dit is nog niet helemaal goed, maar geeft het idee wel weer:
<img width="1163" alt="Screenshot 2024-12-16 at 15 38 41" src="https://github.com/user-attachments/assets/5d5d1264-d8dd-4831-b3fa-bda2ca0a7c53" />

Hiervoor moest ik met name de percentages in de flex en max-width aanpassen zodat er meer op een regel komt. Daarnaast de border en shadow aangepast. Dat is natuurlijk bestaande CSS classes aanpassen ipv de juiste alternatieve CSS classes kiezen, dus is niet 1 op 1 over te nemen._

ik denk niet dat dit beter is

2024-12-17 13:51 UTC, chinook25 requested changes
Found some issues:

- After clicking on one of the filters, the history gets messed up and I need to press back 3 times to get back to the home screen.
- When going back, the query stays in the url, it should be removed when on the home screen.
- Clicking on 'see more detail' for a collection results in a white screen.
- Clicking the 'go to biobank' button results in a white screen.
- There are 4 collections previewed, but there are only 3 in the tables. Should this be dynamic?

2024-12-18 10:34 UTC, chinook25 approved these changes

2024-12-18 13:15 UTC, merged