chore: add error handling on page not found
molgenis/molgenis-emx2 pull request #4573
Opened 2024-12-18 12:29 UTC by chinook25

Now show error instead of infinite spinner when navigating to a biobank/collection/service/study that doesn't exist

### What are the main changes you did
- Added more error handling

### How to test
- Go to an invalid biobank e.g. https://preview-emx2-pr-213421341.dev.molgenis.org/directory-demo/directory/#/biobank/invalid

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

2024-12-19 10:05 UTC, esthervanenckevort requested changes
In het dialoog met de foutmelding heb je een klein kruisje om de fout weg te klikken, waarna je een blanco pagina overhoudt met alleen het menu. Aangezien dit de verschillende details pagina's betreft denk ik dat het beter is om er een echte error pagina van te maken en een knop om terug te gaan naar de catalogus.

In het geval van de biobank pagina blijft er nog een spinner op het scherm staan.

2024-12-19 10:11 UTC, chinook25 commented
> In het dialoog met de foutmelding heb je een klein kruisje om de fout weg te klikken, waarna je een blanco pagina overhoudt met alleen het menu. Aangezien dit de verschillende details pagina's betreft denk ik dat het beter is om er een echte error pagina van te maken en een knop om terug te gaan naar de catalogus.

Zal ik deze PR closen en dat jij daar een feature request voor maakt?

> In het geval van de biobank pagina blijft er nog een spinner op het scherm staan.

Klopt. Is voor een ander PR om te fixen.

2024-12-20 13:52 UTC, mswertz reviewed
code looks good. Just also notice this to be more complex than we would like but you also reported that before.

2024-12-20 13:52 UTC, mswertz commented on apps/directory/src/components/Error.vue
> +      <span v-else style="color: red">
why can the error be something else than string? Is that not the real issue?

2025-01-07 08:56 UTC, esthervanenckevort approved these changes

2025-01-07 12:37 UTC, chinook25 commented on apps/directory/src/components/Error.vue
> +      <span v-else style="color: red">
If an js error occurs it's is not a string but an error object.

2025-01-07 12:38 UTC, merged