changed datamodel (molgenis.csv)
molgenis/molgenis-emx2 pull request #798
Opened 2021-12-14 15:07 UTC by erikzwart

Changed datamodel (molgenis.csv) #8669-4:
VarriableValues -> [SourceVariableValues, TargetVariableValues]
Variables -> [SourceVariables, TargetVariables]
RepeatedVariables -> [RepeatedSourceVariables, RepeatedTargetVariables]

2021-12-23 21:30 UTC, mswertz commented
I am reviewing. I will add observations here.

Observations:
* models are not one-on-one with Networks. Models should exist independent of networks. I.e. need their own name. I would recommend we try to again make SourceTables/TargetTables and SourceVariables/TargetVariables more similar by having both SourceDataDictionaries and TargetDataDictionaries

Slightly less important observations that may take more discussion but are otherwise only window dressing:
* We should think about naming. It is confusing that we use 'resource' and 'source', and confusing that we use 'model' and 'target'. We might reconside to 'source-' and 'cdm-' as prefixes? And thus call models 'CommonDataModels'.

2022-01-03 10:41 UTC, mswertz commented
![](https://github.trello.services/images/mini-trello-icon.png) [#8669-4 releases eruit en variabele model splitsen in collected vs harmonized](https://trello.com/c/sx5RpTjo/328-8669-4-releases-eruit-en-variabele-model-splitsen-in-collected-vs-harmonized)

2022-01-07 20:00 UTC, mswertz commented
I have updated UX, please review.

2022-01-10 14:21 UTC, BrendaHijmans requested changes
-import error messages are not functioning. I am getting "Import failed: Transaction failed: Cannot commit transaction in .....ms." when data is not valid and no specifics are shown. Specifics are shown in other versions of the software for the same data, so this seems to be specific for this PR.
-variable explorer is showing repeated variables separately, this was not the case before. The display of the repeats does not include a variable name (shoudl be taken form the first repeat, which is defined in TargetVariables).
-Cohort view is not showing: "Error: Validation error of type FieldUndefined: Field 'SourceTables_agg' in type 'Query' is undefined @ 'SourceTables_agg'"

2022-01-10 14:32 UTC, connoratrug commented on apps/catalogue/src/store/actions.js
> +    console.log(resp);
remove debug code

2022-01-10 14:41 UTC, connoratrug requested changes
Errors of viewing variable detail

```variableRepository.js:24 fetch variableDetails details failed: Error: Error: Validation error of type FieldUndefined: Field 'fromVariablesInOtherTables' in type 'VariableMappings' is undefined @ 'TargetVariables/mappings/fromVariablesInOtherTables': {"response":{"errors":[{"message":"Error: Validation error of type FieldUndefined: Field 'fromVariablesInOtherTables' in type 'VariableMappings' is undefined @ 'TargetVariables/mappings/fromVariablesInOtherTables'"}],"status":400,"headers":{"map":{"connection":"keep-alive","content-type":"application/json","date":"Mon, 10 Jan 2022 14:39:16 GMT","server":"nginx/1.19.2","transfer-encoding":"chunked"}}},"request":{"query":"query TargetVariables($filter: TargetVariablesFilter) {\n  TargetVariables(limit: 1, filter: $filter) {\n    name\n    label\n    description\n    format {\n      name\n    }\n    unit {\n      name\n    }\n    permittedValues {\n      value\n      label\n      order\n      isMissing\n      ontologyTermIRI\n    }\n    mappings {\n      syntax\n      description\n      match {\n        name\n      }\n      fromDataDictionary {\n        resource {\n          pid\n        }\n      }\n      fromVariable {\n        name\n      }\n      fromVariablesInOtherTables {\n        table {\n          name\n        }\n        name\n      }\n      fromTable {\n        dataDictionary {\n          resource {\n            pid\n          }\n          version\n        }\n        name\n      }\n    }\n    repeats {\n      name\n      mappings {\n        syntax\n        description\n        match {\n          name\n        }\n        fromDataDictionary {\n          resource {\n            pid\n          }\n        }\n        fromVariable {\n          name\n        }\n        fromTable {\n          dataDictionary {\n            resource {\n              pid\n            }\n            version\n          }\n          name\n        }\n      }\n    }\n  }\n}\n","variables":{"filter":{"name":{"equals":"alc"},"dataDictionary":{"equals":[{"resource":{"pid":"LongITools_CDM"},"version":"1.0.0"}]}}}}} ```

2022-01-11 11:21 UTC, mswertz commented
there is also a platform bug because RepeatSourceVariables is fairly long, within queries we go beyond 64 characters. So I believe we need to change SqlQuery class to use short identifiers instead of a meaningful concatenation of table names. Might be tricky :-)

2022-01-12 05:59 UTC, mswertz commented
> -Cohort view is not showing: "Error: Validation error of type FieldUndefined: Field 'SourceTables_agg' in type 'Query' is undefined @ 'SourceTables_agg'"

Did you use correct data model as in the pull request?

2022-01-12 06:43 UTC, mswertz commented
I have updated the pull request to address most issues, can you retest?

2022-01-12 07:52 UTC, connoratrug requested changes
- view variables 
- see list of vars ( lost of lifecycle in example )
- select lifecycle in filter
- expected: only lifecycle vars
- actual: empty variable list

2022-01-12 11:16 UTC, mswertz commented
> -import error messages are not functioning. I am getting "Import failed: Transaction failed: Cannot commit transaction in .....ms." when data is not valid and no specifics are shown. Specifics are shown in other versions of the software for the same data, so this seems to be specific for this PR.

This is a bug that we need to fix

2022-01-12 11:17 UTC, mswertz commented
To fix the repeated variables that are now also shown in the variable-explorer, we will change the data model such that RepeatedTargetVariables are not in the TargetVariables. Therefore create a common superclass table 'AllTargetVariabes' (and for symmetry also AllSourceVariables).

2022-01-12 14:38 UTC, BrendaHijmans approved these changes
variable explorer works after datamodel update.
i found no other issues specific to this PR

2022-01-12 14:46 UTC, connoratrug reviewed
- Go to variable explorer
- view harmonisation grid ( some are green some are not)
- Add filer from tree ( or list  ) that results in empty list 
- Expected; empty list
- Result: spinner

2022-01-12 14:48 UTC, connoratrug reviewed
Padding seems to be missing / inconsistent, suggest to use bs defaults
 
![Screenshot 2022-01-12 at 15 46 45](https://user-images.githubusercontent.com/47183404/149162579-6dc6541d-dcc6-469d-b125-3e385a36300e.png)

2022-01-12 14:49 UTC, connoratrug reviewed
Tree does not take up available space below block, this makes is hard to browse the crapped tree

![Screenshot 2022-01-12 at 15 46 53](https://user-images.githubusercontent.com/47183404/149162784-2f596037-f2be-41b3-ae06-623b8ce64a39.png)

2022-01-12 14:50 UTC, connoratrug reviewed
strange :hover styling

![Screenshot 2022-01-12 at 15 49 02](https://user-images.githubusercontent.com/47183404/149163114-8e9e592b-acbf-4009-82b5-6d25198ab06e.png)

2022-01-12 16:02 UTC, connoratrug approved these changes

2022-01-12 16:03 UTC, connoratrug commented
approved; see notes on empty lists and styling

2022-01-12 20:47 UTC, mswertz commented
Good points from Connor on the layout. Added a story to the backlog to address these.

Meanwhile: bugfix for long table names #871 and bugfix for missing import error message #872 have been made

2022-01-13 09:54 UTC, merged