build: sonar should not show after but before merge stats
molgenis/molgenis-emx2 pull request #944
Opened 2022-02-04 12:46 UTC by mswertz

2022-02-04 16:20 UTC, connoratrug requested changes
when submitting a PR i would like to know the code cov after merge, not before

2022-02-04 23:04 UTC, mswertz commented
But then you dont know how the pull request contributes to change.

2022-02-06 16:21 UTC, connoratrug commented
> Indeed, but you want coverage reported on new code, not on code already in master.
> 
> Therefore I recommend we test what you get when running sonar using jenkins vs using circleci. I get impression you want the result from circleci (which in github links to the result from the PR) and not jenkins (which I get the impression links to the results from the master.

oke , if you mean; remove the jenkins sonar hook, i understand the change

2022-02-06 16:21 UTC, connoratrug approved these changes

2022-02-07 12:24 UTC, merged